### ISSUE TITLE
Error: [$compile:ctreq] Controller 'ngModel', required by directive 'format', can't be found!

### ISSUE THREAD

**Issue by checklist** [indrimuska/angular-moment-picker#10]
Hi,

I am getting the following exception:

Error: [$compile:ctreq] Controller 'ngModel', required by directive 'format', can't be found!

when using:

```
<div class="picker hour-picker" moment-picker="task.dueDate" format="LT" min-view="day" max-view="hour" start-view="day">
	<div layout="row" layout-align="start center">
		<i class="s18 icon icon-clock"></i>
		<span>{{task.dueDate | date:'shortTime'}}</span>
	</div>
</div>
```

If I remove the format="LT" the exception goes away. Any ideas?

**Comment by indrimuska** [comment]
Hi @checklist, it seems that your code needs for a not-provided "format" directive, but I can't help you with just this little piece of code. Could you please provide a full working plunker that shows this issue?
Thanks.

**Comment by checklist** [comment]
My app is a "little too big" to share ;-)

Isn't the "format directive" part of the angular-moment directive? I see it in the documentation. Otherwise, is there another way to set the format returned by the pickers?

**Comment by indrimuska** [comment]
No, Angular Moment Picker has just one directive with the same name (there is no directives with that name, `format` is just a property of the main directive).

But, as you think, you have two ways to change the format of your pickers:
 * using the standard format attribute:
```html
<div moment-picker="myDate" format="YYYY-MM-DD">
    {{ myDate }}
</div>
```
 * using the picker provider (this will apply the format for all the pickers):
```javascript
angular
    .module('myApp', ['moment-picker'])
    .config(['momentPickerProvider', function (momentPickerProvider) {
        momentPickerProvider.options({
            format: 'YYYY-MM-DD'
        });
    }]);
```

Let me know if this could help you :)

**Comment by checklist** [comment]
Hi,

I managed to get rid of the format exception (was due to some code by another developer). The second option is not really an option as I need to use multiple formats. 

I am trying to get it to work as follows: I have two date widgets: one allowing date selection and the second the time selection:

```
						<div class="due-date" layout="row" layout-align="start center">
							<div class="picker day-picker" moment-picker="task.dueDate" min-view="year" max-view="month" start-view="month">
								<div layout="row" layout-align="start center">
									<i class="s18 icon icon-calendar"></i>
									<span>{{task.dueDate | date:'mediumDate'}}</span>
								</div>
							</div>

							<div class="picker hour-picker" moment-picker="task.dueDate" min-view="day" max-view="hour" start-view="day">
								<div layout="row" layout-align="start center">
									<i class="s18 icon icon-clock"></i>
									<span>{{task.dueDate | date:'shortTime'}}</span>
								</div>
							</div>
														
							<div class="remove-due-date" layout="row" layout-align="center center" ng-click="task.dueDate = ''">
								<i class="s16 icon icon-close"></i>
							</div>
```
This is based on http://fuse-angular-material.withinpixels.com/scrumboard/boards/32gfhaf2/acme-frontend-application (click on any card to see it on the popup). The date is stored in task.dueDate as a date object. If I add a format to the moment directive I get a weird constant changing of the set date and time widgets.

Is there a way to contact you privately with a link to our demo? Thanks!

**Comment by indrimuska** [comment]
Yes, of course, shoot me an [email](mailto:indrimuska@gmail.com) or add me on [gitter](https://gitter.im/indrimuska) so we can talk privately.
I will close this issue since it looks like a problem of your app, not in Angular Moment Picker.

**Comment by checklist** [comment]
Hi,

So I am not sure it is a problem with my app. Here is a plunk I made for it: http://plnkr.co/edit/AawSxwhjatiAzhNlW3m5?p=preview . You can see that when using two moments with the same model I get the problem.

Any ideas?
