### ISSUE TITLE
Programmatically fill input

### ISSUE THREAD

**Issue by Bana0615** [indrimuska/angular-moment-picker#100]
I am trying to edit a page using this and i cannot get the input to fill in with data.

```html
<input  class="form-control"
       	ng-model="myCtrl.DateModel"
       	ng-model-options="{ updateOn: 'blur' }"
    	min-view="year"
     	max-view="hour"
	format="YYYY-MM-DD HH:mm"
       	placeholder="Select a date..."
       	moment-picker="myCtrl.data.Date"
	readonly
	required>
```

I have tried setting myCtrl.DateModel and myCtrl.data.Date to "2009-07-15 00:00" and neither work. Help please

**Comment by ericdecarli** [comment]
to populate the input it is expecting a moment object

myCtrl.DateModel = moment(2009-07-15, 'YYYY-MM-DD')

**Comment by Bana0615** [comment]
Thank you that worked!
