### ISSUE TITLE
Days not changing on change of language 

### ISSUE THREAD

**Issue by suchetabiswas** [indrimuska/angular-moment-picker#103]
Hi
I am using the moment picker with month view.  I have set the locale as selected language.
Issue is when I change the language from the language drop down the name of days of the week are not updated and displayed  in the last selected language.
The month name however gets updated.

Looking at the angular-moment-picker.js file, i see that when the Monthview is constructed the days (headers in v0.9.1 ) are created in the constructor. When language is changed the constructor is not called. So language is not updated.

Can you please take a look at this?

**Comment by indrimuska** [comment]
Hi @suchetabiswas you're completely right about that.
Actually I cannot prepare a fix till next week, but I absolutely pack one and get back to you.
If you need a quick solution, you can just move header initialization in the `render` method.
Thanks for reporting this.

**Comment by suchetabiswas** [comment]
Great thak you for looking into it!

**Comment by indrimuska** [comment]
FYI, this fix will be available in the next release.

**Comment by indrimuska** [comment]
Latest release [v0.9.2](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.9.2) is now out.
