### ISSUE TITLE
Picker broken by minification

### ISSUE THREAD

**Issue by destegabry** [indrimuska/angular-moment-picker#104]
I'm using Gulp to create a build of my Angular app, unluckily seems that your directive is broken by the minification.
This error is logged in each page containing the `moment-picker` directive.
```
TypeError: Cannot read property 'isAfterOrEqualMin' of undefined
    at Object.isSelectable (http://localhost:3000/scripts/vendor-7cd641134b.js:283:3615)
    at http://localhost:3000/scripts/vendor-7cd641134b.js:283:20461
    at Array.forEach (native)
    at e.render (http://localhost:3000/scripts/vendor-7cd641134b.js:283:20391)
    at render (http://localhost:3000/scripts/vendor-7cd641134b.js:283:7731)
    at r (http://localhost:3000/scripts/vendor-7cd641134b.js:8:10294)
    at y.$eval (http://localhost:3000/scripts/vendor-7cd641134b.js:8:13163)
    at y.$digest (http://localhost:3000/scripts/vendor-7cd641134b.js:8:11636)
    at t.$apply (http://localhost:3000/scripts/vendor-7cd641134b.js:8:13446)
    at HTMLTableCellElement.<anonymous> (http://localhost:3000/scripts/vendor-7cd641134b.js:10:20511)
```
The picker shows an empty calendar:
<img width="385" alt="schermata 2016-12-29 alle 19 06 25" src="https://cloud.githubusercontent.com/assets/4654358/21550408/f5660846-cdf9-11e6-9bf6-73a68ff90fec.png">

When clicking on the arrows the same error as before is thrown.

The build task is configured as follows:
```javascript
gulp.task('build', build);

function build() {
  const partialsInjectFile = gulp.src(conf.path.tmp('templateCacheHtml.js'), {read: false});
  const partialsInjectOptions = {
    starttag: '<!-- inject:partials -->',
    ignorePath: conf.paths.tmp,
    addRootSlash: false
  };

  const htmlFilter = filter(conf.path.tmp('*.html'), {restore: true});
  const jsFilter = filter(conf.path.tmp('**/*.js'), {restore: true});
  const cssFilter = filter(conf.path.tmp('**/*.css'), {restore: true});

  return gulp.src(conf.path.tmp('/index.html'))
    .pipe(inject(partialsInjectFile, partialsInjectOptions))
    .pipe(useref())
    .pipe(jsFilter)
    .pipe(ngAnnotate())
    .pipe(uglify({preserveComments: uglifySaveLicense})).on('error', conf.errorHandler('Uglify'))
    .pipe(rev())
    .pipe(jsFilter.restore)
    .pipe(cssFilter)
    .pipe(cssnano())
    .pipe(rev())
    .pipe(cssFilter.restore)
    .pipe(revReplace())
    .pipe(htmlFilter)
    .pipe(htmlmin())
    .pipe(htmlFilter.restore)
    .pipe(gulp.dest(conf.path.dist()));
}
```

Any idea on how to solve?

**Comment by indrimuska** [comment]
Hi @destegabry
Which revision the picker are you using?
Can you please provide me a compiled version of one of the pages of your app?
Thanks

**Comment by destegabry** [comment]
I'm using the latest (0.9.1), here's a minified page with the issue
[dist.zip](https://github.com/indrimuska/angular-moment-picker/files/678418/dist.zip)

**Comment by indrimuska** [comment]
Ok, what about this?

> Can you please provide me a compiled version of one of the pages of your app?

**Comment by suchetabiswas** [comment]
I am facing the exact same issue with the latest version.

**Comment by indrimuska** [comment]
OK, I am now able to see the error and it seems to be related to the way gulp applies minification (in particular the way it generates `view.isSelectable` method of the internal directive scope).

Do your gulp sources include minified or full version of the javascript file of the project?

**Comment by indrimuska** [comment]
Since I've started learning Gulp just for this issue, someone of you -@destegabry or @suchetabiswas- can provide me an executable gulpfile.js I can use to find a solution for this?
Thanks :)

**Comment by destegabry** [comment]
My configuration attached, it might be a little oversized for this use case!
[gulp.zip](https://github.com/indrimuska/angular-moment-picker/files/692982/gulp.zip)

**Comment by indrimuska** [comment]
Thank you @destegabry.
Please contact me on [gitter](https://gitter.im/indrimuska) so we can chat directly to resolve this.
Thanks! :)

**Comment by destegabry** [comment]
I written to @indrimuska on gitter but received no response

**Comment by indrimuska** [comment]
Sorry, I was not receiving any notification from Gitter for a month!
I've just seen your request, I'll answer you asap.

**Comment by claus1982** [comment]
I have the same problem, any news?

**Comment by indrimuska** [comment]
No, not yet. Actually I am unable to reproduce this issue. @claus1982 you can contact me directly on gitter, since @destegabry is quite busy in this period.

**Comment by ShankzPatil** [comment]
# my vendor js line 744: 

"rightArrow","additions"],function(e){n.isDefined(t[e])||(t[e]=u.provider[e]),n.isDefined(i[e])||(i[e]=t[e])}),i.ngModel||(l={}),t.limits={minDate:o.toMoment(t.minDate,t.format,t.locale),maxDate:o.toMoment(t.maxDate,t.format,t.locale),isAfterOrEqualMin:function(e,i){return!n.isDefined(t.limits.minDate)||e.isAfter(t.limits.minDate,i)||e.isSame(t.limits.minDate,i)},isBeforeOrEqualMax:function(e,i){return!n.isDefined(t.limits.maxDate)||e.isBefore(t.limits.maxDate,i)

# and your min.js line 744:3415
"rightArrow","additions"],function(t){o.isDefined(e[t])||(e[t]=d.provider[t]),o.isDefined(i[t])||(i[t]=e[t])}),i.ngModel||(l={}),e.limits={minDate:a.toMoment(e.minDate,e.format,e.locale),maxDate:a.toMoment(e.maxDate,e.format,e.locale),isAfterOrEqualMin:function(t,i){return!o.isDefined(e.limits.minDate)||t.isAfter(e.limits.minDate,i)||t.isSame(e.limits.minDate,i)},isBeforeOrEqualMax:function(t,i){return!o.isDefined(e.limits.maxDate)||t.isBefore(e.limits.maxDate,i)||t.isSame(e.limits.maxDate,i)},isSelectable:function(t,i){

after gulp minification e is replace by t and vice versa.

**Comment by mouss-delta** [comment]
Hi,

First of all I would like to thank you  indrimuska for your great job, this module is amazing!

Unfortunately I am facing exactly the same issue, is there any update concerning this issue?

Thanx

**Comment by domalak** [comment]
I had this problem too. I solved it by telling Gulp to use `angular-moment-picker.js` instead of `angular-moment-picker.min.js` which was taken by default.

**Comment by selectedpixel** [comment]
@mouss-delta Your suggestion definitely makes the error go away, although the picker no longer works for me so it's not really a solution.

**Comment by mouss-delta** [comment]
Hi @selectedpixel, have you tried @domalak solution? It works fine for me. 

Here is how I do it, in bower.json I added this :

"overrides": {
    "angular-moment-picker" : {
      "main": [
        "dist/angular-moment-picker.js",
        "dist/angular-moment-picker.css"
      ]
    }
}

**Comment by selectedpixel** [comment]
@mouss-delta I'll see if I can get that to work.

**Comment by selectedpixel** [comment]
@mouss-delta That worked. I think it goes without saying this is still a pretty large issue though.

**Comment by byakuya93** [comment]
Hi @indrimuska, I am not sure you are receiving gitter notifications, please have a look to our discussion in gitter, I have set a little project that reproduce the issue.

**Comment by mouss-delta** [comment]
Hi @indrimuska, I am not sure you are receiving gitter notifications, please have a look to our discussion in gitter, I have set a little project that reproduce the issue.

**Comment by indrimuska** [comment]
Thanks @mouss-delta for the useful sample provided. 👍 

I confirm that this issue is caused by the [`grunt-uglify`](https://www.npmjs.com/package/gulp-uglify) plugin when it tries to uglify a minified js file. Basically there's nothing I can change to help you with this. My advice is to make the repo maintainers aware of this bug and hope they solve this for you :)

Anyway, I suggest to replace the plugin with any valid alternative. I've already test [`gulp-minify`](https://www.npmjs.com/package/gulp-minify) and it seems to works like a charm. Hope this helps.

**Comment by ederfranco23** [comment]
@mouss-delta , your solution worked like a charm! Thanks!

**Comment by sharrondenice** [comment]
@mouss-delta your solution worked for me as well! Thank you so much!

**Comment by zios07** [comment]
@mouss-delta you saved my day. Thanks !

**Comment by arunthamizh94** [comment]
Thanks for all I change minified CDN (https:/angular-moment-picker.min.js ) to un-minified CDN (https:/angular-moment-picker.js ) it's working for me

**Comment by arkiski** [comment]
@mouss-delta i owe you a beer! Thanks for the tip!

**Comment by raoulsigne** [comment]
@moussa-b you saved me long days struggling on google. thanks
