### ISSUE TITLE
Can't get minutes-step to work

### ISSUE THREAD

**Issue by F0r3v4R** [indrimuska/angular-moment-picker#106]
Specifying minutes-step doesn't seem to change the selectable minutes on the hours view.  Instead, the default step of 5 minutes is presented.  I'm not sure if this is actually broken or i'm just doing something completely idiotic.

<input class="form-control"
                              moment-picker="ctrl.startDateTime"
                              ng-model="ctrl.startDateTime"
                              start-view="month"
                              minutes-step="15"
                              max-date="ctrl.endDateTime"
                              validate="true"
                              ng-model-options="{ updateOn: 'blur' }">

![image](https://cloud.githubusercontent.com/assets/9371454/21651260/f0ea4a22-d275-11e6-902c-a875f057f7b7.png)

Relevant plunker: https://plnkr.co/edit/ZIHliUTDI5Fdq45nDQTa?p=preview

And thoughts would be appreciated!

**Comment by indrimuska** [comment]
Hi @F0r3v4R , as you can see fron the README, that option is not included in the directive attributes set, it's only part of the Moment Picker Provider: https://github.com/indrimuska/angular-moment-picker#momentpickerprovider

```
.config ('momentPickerProvider', function (provider) {
   provider.options ({
      mintesStep: 5
   });
});
```

**Comment by guygilboa** [comment]
It's working but you have mistake with the property name. It's "minutesStep" and not  "mintesStep"

**Comment by himanshumittal90** [comment]
I had the same problem so below solution works for me, 
changes in angular-moment-picker.min.js file 
minutesStep: "=?", // define it in scope

wherever you find this.provider.minutesStep change it to this.$scope.minutesStep || this.provider.minutesStep

and then pass value from specific element like minutes-step="15"

it will work. If not then contact me on [himu.mittal23@gmail.com](mailto:himu.mittal23@gmail.com)
