### ISSUE TITLE
Warn about the bower package to avoid confusing with angular-moment-picker

### ISSUE THREAD

**Issue by pdorgambide** [indrimuska/angular-moment-picker#109]
I just falled into the tramp. ;o).

bower install **moment-picker**

**Warnning**: This should not be confused with _angular-moment-picker_

**Comment by indrimuska** [comment]
Thank you @pdorgambide, you're not the only one who had this problem.
I don't know if it is possible to show such a warning to those who use bower to get this package.

Anyway, the only think you all can do is to warn the other [repo maintainers](https://github.com/alanjhonnes/angular-moment-picker) to avoid this type of misunderstanding.
Thanks :)
