### ISSUE TITLE
Troubles with locales

### ISSUE THREAD

**Issue by AKFourSeven** [indrimuska/angular-moment-picker#11]
I am having difficulties with locales at the moment. 
I am using angularjs 1.4.4. and I just thought of using your directive for solve conversion issues.
I have install through Bower momentJS and included in my javascript moment-with-locales.
My issue is that whenever I try to set my locale to France (by using 'fr') the date coming from the model that is printed always shift back to a default format that looks like the following Fri Jan 01 2016 01:00:00 GMT+0100 (CET) instead of the format given which is 2016-01-01, but when I select a date on the picker, it prints correctly.

Here are snippets of my code (the different scripts are big so I cannot share the whole thing):

**index.html**
```html
<!doctype html>
<html class="no-js">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- <base href="/wsh#/" /> -->
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <!-- build:css(.) styles/vendor.css -->
    <!-- bower:css -->
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="bower_components/ng-table/dist/ng-table.min.css" />
    <link rel="stylesheet" href="bower_components/angular-moment-picker/dist/angular-moment-picker.min.css" />
    <!-- endbower -->
    <!-- endbuild -->
    <!-- build:css(.tmp) styles/styles.css -->
    <link rel="stylesheet" href="styles/styles.css">
    <!-- endbuild -->
  </head>
  <body ng-app="myApp">
  <script src="bower_components/jquery/dist/jquery.js"></script>
    <script src="bower_components/angular/angular.js"></script>
    <!-- quantity of library -->
    <script src="bower_components/moment/min/moment-with-locales.js"></script>
    <script src="bower_components/angular-moment-picker/dist/angular-moment-picker.min.js"></script>
    <!-- endbower -->
    <script src="bower_components/messageformat/locale/fr.js"></script>
    <script src="bower_components/messageformat/locale/en.js"></script>
    <!-- endbuild -->
    <!-- build:js({.tmp,app}) scripts/scripts.js -->
    <script src="https://code.angularjs.org/1.4.4/i18n/angular-locale_en.js"></script>
    <script src="https://code.angularjs.org/1.4.4/i18n/angular-locale_fr-fr.js"></script>
    <!-- quantity of scripts -->
    <!-- endbuild -->
</body>
```

**app.js**
```javascript
angular.module('washingtonApp', [
                                 'pascalprecht.translate',
                                 'moment-picker'])
.config(function ($stateProvider, $translateProvider, $translatePartialLoaderProvider, toastrConfig, momentPickerProvider) {
    $stateProvider.state('root', {url: '/:navId', abstract: true, template: '<ui-view/>'});
    $translatePartialLoaderProvider.addPart('core');
    $translateProvider.useLoader('$translatePartialLoader', {
        urlTemplate: '/i18n/{part}/{lang}.json'
    });
    $translateProvider.usePostCompiling(true);
    $translateProvider.useMessageFormatInterpolation();
    $translateProvider.fallbackLanguage('fr');
    $translateProvider.useSanitizeValueStrategy('escapeParameters');
    angular.extend(toastrConfig, {
        closeButton: true,
        autoDismiss: true,
        maxOpened: 10,
        showDuration: 300,
        newestOnTop: false,
        positionClass: 'toast-bottom-right'
    });
    momentPickerProvider.options({
       /* Picker properties */
       // locale:        'fr',
       format:        'YYYY-MM-DD',
       startView:     'day'
   });
})
```

**in a view**
```html
<input ng-model="vm.contract.signature_date" moment-picker="vm.contract.signature_date" placeholder="{{'PLACEHOLDERS.DATE' | translate}}" name="signatureDate" id="signatureDate" aaf-label="{{'CONTRACT.EDIT.SIGNATURE_DATE'| translate}}"
                                    waaf-group-class="col-md-4 col-xs-5" waaf-valid-hlp-block="pages/contracts/date-messages.hlp.html" max="{{vm.today}}" required/>
```

additionally I tried to set a watcher on this input, that look as the following:
```javascript
scope.$watch(function(){ return ctrl.contract ? ctrl.contract.signature_date : null; }, function(newValue, oldValue){
                if(newValue === oldValue || !newValue){
                    return;
                }
                newValue = moment(newValue).format("YYYY-MM-DD");
                ctrl.signature_date = newValue;
            });
```

**Comment by indrimuska** [comment]
Hello @AKFourSeven.
I can't find any trouble using moment picker provider, as you can see at this [plunker](http://plnkr.co/edit/gXZjIE1Y7zZo0LAxuYVg?p=preview), it may helps you to understand the problem.

I was looking at your code and I noticed something strange I can't figure out:
 1. Your input model is `vm.contract.signature_date`, so I could think that you have a controller with alias `vm`. Why didn't you use the simple expression `$watch('vm.contract.signature_date')` in your watcher?
 2. Also, I don't understand why you create a moment object to get the same format of the parsed input. I mean, in your watcher callback you did `moment(newValue).format("YYYY-MM-DD")`, but `newValue` already has the format `YYYY-MM-DD`.
 3. You assigned `newValue` to `ctrl.signature_date`. It shouldn't be `ctrl.contract.signature_date`?

**Comment by AKFourSeven** [comment]
1. It would make the assumption that vm.contract is already set, which is not always the case.

2. That is precisely the issue, and I apologies for not making it clearer, we send a particular format to the webservices so that it can be correctly read by the backend tier, then when we read the value it is converted back to proper angularjs format date, but it does not print correctly.

3. No that was correct, but I realised that (as it was not originally my code) I was not hitting the correct function, it was in an entirely different place, so I manage to correct the issue and there was nothing wrong with the plug-in, just me not being thourough enough in my analysis of the code.

**Comment by indrimuska** [comment]
Glad to hear you figure out your problem!
I'm going to close this issue.
