### ISSUE TITLE
Uncaught ReferenceError: moment is not defined

### ISSUE THREAD

**Issue by simonemazzoni** [indrimuska/angular-moment-picker#110]
Hello,

I installed this modules but when I try to use it registering the angular modules, it gives me this runtime error.

`Uncaught ReferenceError: moment is not defined`

Any idea?

**Comment by ChrisGarber-Medlever** [comment]
I'm also getting this error. Our build process doesn't use node so I copied the file from dist to where we keep our scripts and on build I see that in the terminal. It appears to be the moment provider, but I don't know enough about webpack to diagnose what should be done. I have Moment.js in the same folder so it should be available.

**Comment by ChrisGarber-Medlever** [comment]
Just worked it out for us, it was a problem with our ASP bundling, you need to make sure it's in the same bundle (or a later bundle) with moment.js (it was in our angular bundle, which is why I wasn't getting an error for angular).

**Comment by simonemazzoni** [comment]
I've just figured out the problem. It was a webpack problem. I use a provider to include moment to webpack bundle and in my configuration moment was placed in `window.moment` in place of `moment`, and since this module search moment in a variable called `moment` he wasn't able to find it.
