### ISSUE TITLE
format="LT" date gets reset to now

### ISSUE THREAD

**Issue by marcgetqd** [indrimuska/angular-moment-picker#114]
I have am using two instances of the`moment-picker` directive. 

One is to select the date, one is to select the time.

When the format is set to `LT` it disregards the date in the scope and resets it to now, but it keeps the time as is.

![screen-shot-2017-01-12-at-5 53 57-pm](https://cloud.githubusercontent.com/assets/18057718/21914526/2504faa6-d8f1-11e6-892e-6dcfea555501.jpg)

Is there a way to either

- a) have the proper date show up at the top of the time picker
- b) remove the date and arrows at the top

There is an `ng-if="showHeader` on the moment picker header view, but no parameters listed. `showHeader = false` has no effect on the element.

I can remove it with CSS for the time being, which is kind of annoying but manageable.

**Comment by indrimuska** [comment]
Hi @marcgetqd, you can do both with Angular Moment Picker.

- a) Use the same ngModel variable for both picker, but different momentPicker variable (and also different formats)
- b) Add `show-header="true"` attribute

**Comment by indrimuska** [comment]
Damn, showHeader has been missed after one of my refactoring.
Sorry, let me fix this in a minute.

**Comment by indrimuska** [comment]
This fix will be released on the next version.

**Comment by indrimuska** [comment]
FYI [v0.9.4](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.9.4) is now out.

**Comment by marcgetqd** [comment]
Thanks @indrimuska, also just so you know, if you use two different pickers, one for date and one for time with the same ng-model, when you update the date it resets the time to 12:00AM on the timepicker

**Comment by indrimuska** [comment]
Just pushed a new release of the picker ([0.9.5](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.9.5)), this should allow using the same model across multiple pickers.

**Comment by indrimuska** [comment]
Check out this plunker: https://plnkr.co/edit/MqdNy1?p=preview
