### ISSUE TITLE
display datepicker at right side of the input element

### ISSUE THREAD

**Issue by sadashivm** [indrimuska/angular-moment-picker#116]
Hi,
is their any configuration for display datepicker at right side? . now currenlty it is showing at left side.

i added bellow code

```
<md-input-container md-no-float ng-style="{'margin-top':'-5px', 'margin-bottom': '0px', 'width' : dp.customWidth, 'height':'20px'}">
    <input type="text" style="height:3px;" ng-keydown="keydownevent($event)">
        <i class="fa fa-calendar" aria-hidden="true" style="float: right;margin-top: -16px;color: #95a6a4;cursor:pointer;" change="selectYear()" moment-picker="dpValue" format="{{dp.dateFormat}}"></i>
</md-input-container>
```
for reference find the screen shot
![untitled](https://cloud.githubusercontent.com/assets/10355473/21972811/48e425e8-dbe2-11e6-9295-be9ab9ef9ea3.png)

**Comment by indrimuska** [comment]
Hi @sadashivm,
the picker is appended to the element that contains the `moment-picker` attribute.
Can you try to move the attribute to the md-input-container directive?
Thanks

**Comment by indrimuska** [comment]
I'm going to close this issue since no answer has been provided.
