### ISSUE TITLE
show-header="false" is not working

### ISSUE THREAD

**Issue by yasirrafiq33** [indrimuska/angular-moment-picker#117]
Hi indri...

I have placed to input one for date and one for time. Once I select date then in time picker date should come in header. But time picker header is showing today date.
If this is not happened then how can I header as false. Like I don't want to show in time picker.

Regards
Yasir

**Comment by indrimuska** [comment]
This is already fixed and will be published in the next release.
Thanks. :)

**Comment by indrimuska** [comment]
FYI [v0.9.4](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.9.4) is now out.

**Comment by yasirrafiq33** [comment]
When you will publish?
