### ISSUE TITLE
Css issue

### ISSUE THREAD

**Issue by checklist** [indrimuska/angular-moment-picker#12]
Hi,

I am trying to build my project and it fails on the css of this library (csso gulp). It specifically points to these lines:

```
moment-picker { position: relative; }
.moment-picker .moment-picker-contents { cursor: pointer; }
.moment-picker .moment-picker-container { color: #404040; min-width: 15em; background: #fff; padding: 4px; border: 1px solid #f0f3f4; border-radius: 4px; position: absolute;
	top: 100%; margin-top: 4px; margin-left: -.5em; box-shadow: 0 2px 4px rgba(0, 0, 0, .075); z-index: 5; }
.moment-picker .moment-picker-container:before,
.moment-picker .moment-picker-container:after { content: ''; display: block; width: 0; height: 0; border: 8px solid transparent; border-top: none; position: absolute;
	top: -9px; left: 15px; }
.moment-picker .moment-picker-container:before { border-bottom-color: #f0f3f4; border-width: 9px; }
.moment-picker .moment-picker-container:after { border-bottom-color: #fff; margin-top: 1px; margin-left: 1px; }
.moment-picker table { border-collapse: collapse; border-spacing: 0; width: 100%; table-layout: fixed; }
```

When I run the code through a css validator (https://jigsaw.w3.org/css-validator/validator) I get the following errors:

> URI : TextArea
> 7	.moment-picker .moment-picker-container:before, .moment-picker .moment-picker-container:after	Lexical error at line 7, column 31. Encountered: "?" (63), after : "" ;??}
> 9	.moment-picker .moment-picker-container:after	Lexical error at line 9, column 110. Encountered: "?" (63), after : "" ;??}
> 

Any idea?

**Comment by checklist** [comment]
After a lot of research, it seems like the build process of the plugin is somewhere faulty and the generated css is not valid but also different than the original. Minification?

**Comment by indrimuska** [comment]
Ok @checklist, I know what this is caused. This is due to the keyboard combination ALT+SPACE on mac that generates a non-breaking space character (0xA0) instead of a normal space (0x20).
Give me five to replace all these characters.

**Comment by indrimuska** [comment]
Let me know if this causes troubles to you yet. :)
