### ISSUE TITLE
output not displaying correct

### ISSUE THREAD

**Issue by programmingjam** [indrimuska/angular-moment-picker#120]
<div>
                                <input type="text" id="endTimeStamp"
                                       ng-model="endTimeStamp"
                                       class="form-control"
                                       maxlength="40"
                                       required="required"
                                       moment-picker="ctrl.endTimeFormatted"
                                       format="YYYY-MM-DDTHH:mm:ss.sssZ"
                                >
                            </div>
The format works perfect with moment.js but when add the date picker it does not!

example: 
wrong output with date picker {startTimeStamp":"2016-12-28T15:41:26.163Z","endTimeStamp":"2017-01-27T15:41:26.164Z"}
correct output from moment.js without datepicker:
{startTimeStamp":"2016-12-28T09:58:06.000-0600","endTimeStamp":"2017-01-27T09:58:06.000-0600"}
any ideas how I can correct this,

here is the code for the one without date picker  

var date = moment().subtract(30,'days').format();
            $scope.startTimeStamp = $filter('date')(date, 'yyyy-MM-ddTHH:mm:ss.sssZ');

            var endDate = moment().format();
            $scope.endTimeStamp = $filter('date')(endDate, 'yyyy-MM-ddTHH:mm:ss.sssZ');

            $scope.NazirFunc = function(){
                $scope.showSpinner = true;
                var tempData = {
                    partyId: $scope.partyId,
                    guId: $scope.guids,
                    cehEnv: $scope.evn,
                    startTimeStamp: $scope.startTimeStamp,
                    endTimeStamp: $scope.endTimeStamp,
                    eventFilter: $scope.eventFilter,
                    selectedSts: $scope.selectedSTS,
                    ecommToken: "",
                    formNumber : "4"
                };
and with the date picker I used the format in the html instead and commented out the first 4 lines and removed the filter example:

                           <div>
                                <input type="text" id="endTimeStamp"
                                       ng-model="endTimeStamp"
                                       class="form-control"
                                       maxlength="40"
                                       required="required"
                                       moment-picker="ctrl.endTimeFormatted"
                                       format="YYYY-MM-DDTHH:mm:ss.sssZ"
                                >
                            </div>
Thanks,
Jim

**Comment by indrimuska** [comment]
Hi @programmingjam, `format` allowed are those from Moment.js.
In your case `YYYY-MM-DDTHH:mm:ss.sssZ` is not what you think, 'cause `Z` token is the timezone number, instead of the "Z" characted. You should use `[Z]` instead.

As you surely know, this is not due to the picker, but it is all driven by moment.js:
```javascript
moment().format('YYYY-MM-DDTHH:mm:ss.sssZ')
// outputs "2017-02-03T00:18:39.3939+01:00"
moment().format('YYYY-MM-DD[T]HH:mm:ss.sss[Z]')
// outputs "2017-02-03T00:18:39.3939Z"
```
