### ISSUE TITLE
Class for days out of (before or after) current month

### ISSUE THREAD

**Issue by slacktracer** [indrimuska/angular-moment-picker#121]
I just forked and as I need to style days (in month view) before and after current month I coded a minor change.

Are you interested in pull requests?

All I did was change this:

```
class: [
  this.$scope.keyboard && day.isSame(this.$scope.view.moment, 'day') ? 'highlighted' : '',
  !!this.$scope.today && day.isSame(new Date(), 'day') ? 'today' : '',
  !selectable || day.month() != month ? 'disabled' : isValidMoment(this.$ctrl.$modelValue) && day.isSame(this.$ctrl.$modelValue, 'day') ? 'selected' : ''
].join(' ').trim(),
```

to this:

```
class: [
  this.$scope.keyboard && day.isSame(this.$scope.view.moment, 'day') ? 'highlighted' : '',
  !!this.$scope.today && day.isSame(new Date(), 'day') ? 'today' : '',
  !selectable ? 'disabled' : isValidMoment(this.$ctrl.$modelValue) && day.isSame(this.$ctrl.$modelValue, 'day') ? 'selected' : '',
  day.month() != month ? 'other' : ''
].join(' ').trim(),
```

This way I can, e. g., hide the days that there are not of the current (showing) month.

Say:

```
.moment-picker td.other {
  visibility: hidden;
}
```

So if you care about this "feature", let me know...

**Comment by indrimuska** [comment]
Hi @slacktracer, thanks for this proposal, but I would prefer to have the ability to click on the previous month (if visibile), I think it is works better in terms of UX.
Thanks :)

**Comment by slacktracer** [comment]
@indrimuska 

Ok, sure. =)

The visibility thing was just an example. What I am going for in my fork is the **possibility** of styling them differently, if ever necessary. (It is in my particular case.)

Anyway, thank you very much. Great piece of code, mate!

**Comment by AronGreen** [comment]
@indrimuska, will you reconsider this option? 
Right now it seems to be impossible to have different styles for days in future month and days that are not selectable, as there is no difference between the two types of days to style against.
