### ISSUE TITLE
Not formatting initial value

### ISSUE THREAD

**Issue by DickSwart** [indrimuska/angular-moment-picker#127]
When I set the initial model value to moment() the date is not formatted in the View, only gets formatted once you change the date.

**Comment by nurhasyim354** [comment]
Hello, 
Any suggestion for us to fix this issue?

Thank you

**Comment by indrimuska** [comment]
Hi guys, initial value is set from the model, you just need to set the variable you attach to the ngModel property properly. On the other side, if you use dates as string you have to set the property attached to `momentPicker`.

```html
<!-- Moment.js object date -->
<input moment-picker ng-model="momentDate" format="YYYY-MM-DD">

<!-- Formatted string (ngModel is mandatory when using <input>) -->
<input moment-picker="formattedDate" format="YYYY-MM-DD" ng-model="momentDate">
```

```javascript
$scope.momentDate = moment(/*...*/);
// or
$scope.formattedDate = moment(/*...*/).format('YYYY-MM-DD');
```

You can also use both variables together and let the picker handles the updated from one to another. ;)

**Comment by indrimuska** [comment]
I'm going to close this issue, feel free to ping me for any trouble! :)

**Comment by DickSwart** [comment]
Thank you @indrimuska, works fine with input. But it don't work when using a div.

**Comment by indrimuska** [comment]
@DickSwart can you please try to update the picker to the latest version and let me know if everything works as expected? Thanks. :)
