### ISSUE TITLE
How to trigger an "open" event ?

### ISSUE THREAD

**Issue by Fabiencdp** [indrimuska/angular-moment-picker#128]
Hi ! 

Is there a way to trigger an event and open a datepicker ? 

For exemple, i have two datepicker on the same page ( start / end ), i want to automatically open my "end" datepicker after user have chose the start date.

Thanks for your help !

**Comment by indrimuska** [comment]
Hi @Fabiencdp, yes you can do that.
Actually the picker will be opened when you focus the `<input>` field (or any element you use, e.g., `<div>`) or by setting the `isOpen` property to true. This last property (check out [readme](https://github.com/indrimuska/angular-moment-picker/blob/master/README.md#options) for more infos) contains the actual opening state of the picker, so it will be unset when the picker will be closed.

Hope this helps :)
