### ISSUE TITLE
Popup calendar has extra days in it

### ISSUE THREAD

**Issue by dorono** [indrimuska/angular-moment-picker#13]
Cancelling my question below, as I discovered that this issue was specific to my specific implementation and was able to solve the issue, so no bug to report here. :)

~~Hello there,~~

~~I am running into an issue whereby the calendar that pops up upon me clicking on the input field has the beginning of the following month inserted into the calendar along with the last day of the following month. The bug only occurs for the *current* month, and when I navigate to the following month, the calendar displays correctly.~~

~~I know that's confusing, so you can check out the attached screenshot to see what I mean.~~

![angular-moment-calendar-bug](https://cloud.githubusercontent.com/assets/2634159/13092564/3eeb63ae-d4c6-11e5-9cef-dc0962c2ac33.png)

~~Unfortunately, since I am working in a very large codebase with many files possibly affecting the datepicker part of the application, I am not able to put together an online example, however, here is how I am calling it:~~

~~`<input type="text" name="{{'date' + exceptionHour.$originalIndex}}"
    ng-model="exceptionHour.date" 
    moment-picker="exceptionHour.date" 
    format="YYYY-MM-DD"
    start-view="month"
    max-view="month"
    ng-required="exceptionHour"
    ng-model-options="{timezone: 'UTC'}"
    ng-resource="exceptionHour"
    lo-hour-exception-overlap
    items="hours.$exceptions">`~~

~~Has anyone run into this issue before?~~

~~Thanks!~~

**Comment by indrimuska** [comment]
Hi @dorono, sorry for looking this so far. I'm happy to see you've solved your issue! :)
