### ISSUE TITLE
icon click in the chrome browser does not work

### ISSUE THREAD

**Issue by junlight** [indrimuska/angular-moment-picker#130]
icon click in the chrome browser does not work.

icon click does not work when opening the homepage(http://indrimuska.github.io/angular-moment-picker/) as a chrome browser.

--------------------------------------------------------------------------------------------------------------
homepage sameple
--------------------------------------------------------------------------------------------------------------
```html
<div class="input-group"
     moment-picker="ctrl.datepicker"
     format="YYYY-MM-DD">
    <span class="input-group-addon">
        <i class="octicon octicon-calendar"></i>
    </span>
    <input class="form-control"
           placeholder="Select a date"
           ng-model="ctrl.datepicker"
           ng-model-options="{ updateOn: 'blur' }">
</div>
```

but icon click in the explorer browser does work.

chrom browser version : 56.0.2924.87

**Comment by indrimuska** [comment]
Hi @junlight, the fix will be published in the next release.
