### ISSUE TITLE
Question: How to post date in ISO format

### ISSUE THREAD

**Issue by gsonego** [indrimuska/angular-moment-picker#131]
Hi guys, how are you ?

I really liked this datepicker, it has been a hard work trying to find something good for angular.. 
But, It does not fullfill my needs.. I'd like to work with a specific locale (pt-BR) and to format date like this "dd/MM/yyyy" but when I try to use model value it is formatted and not in ISO format, so I'm facing problem posting data to the server.. 

Any Ideas ?

**Comment by ChrisGarber-Medlever** [comment]
You could take advantage of both the locale and format settings included. Something like this:

<moment-picker="foo"
format="LLLL"
locale="pt-br">

or if you want it to display UTC dates

<moment-picker="foo"
format="moment.ISO_8601"
locale="pt-br">

**Comment by gsonego** [comment]
Hi, tks but maybe I didn't make myself clear.. 
I have no problem "formatting" or "localing", they are working fine..
My problem here is to use model value when posting because at this moment I need a ISO format date so server can't understand.. 

I have used in another project the 'parsers' and 'formatters' inside directive so, model has a 'model value' and a different 'view value'.. I thought it could be the same here, when I choose a date, I have a Javascript date object which I can send to the server, but for presentation purposes, the "format" attribute takes place.. 

Do you guys know if that is possible whith this datepicker ?

**Comment by ChrisGarber-Medlever** [comment]
I'm not quite sure what your use case is, but I'm actually in a similar scenario. I have dates coming to me from the server in UTC, which I then need to display in the picker and send back to the server in UTC. I do something like this:

<input moment-picker='fooString'
    ng-model='fooMoment'
    format='yourDisplayFormat'
    locale='yourLocale'
    change='sendDate(newValue, oldValue)'>

and your controller would have something like:

`$scope.sendDate(newDate, oldDate){
    var isoDate = fooMoment.toISOString()
   $http.post(...)
}`

What this does is keeps an up to date moment object in fooMoment. The format property is in essence the "viewValue" format and the moment is the "modelValue". Of course you don't have to send the date every time it changes, that was just an example. All you need to do is reference fooMoment and you will have the moment object.

This doesn't however solve the problem of _parsing_ ISO dates you get. For that you'll probably want to update fooMoment manually, this example is with a watch, but it could be in the get function:

`$scope.$watch('response', function(newVal){ fooMoment =  moment(newVal)}`

I hope this helps!

**Comment by indrimuska** [comment]
Hi @gsonego, what @ChrisGarber-Medlever said is correct!

You can handle with Moment.js object dates in the way you want just by adding `ng-model` aside with `moment-picker`. This will allow use both formatted date string and Moment.js object date. So, in your case you can simply parse the date from ISO to Moment when initializing the Controller and format back to ISO string when submitting the form.

Let's say you have an app that shows a calendar with a list of Events.

```javascript
app.controller('MyController', ['eventService', function (eventService) {
    var ctrl = this;

    // format used in the view
    ctrl.dateFormat = 'DD/MM/YYYY';

    // init event
    eventService.getEvents().then(function (events) {
        // get just first event
        ctrl.event = events[0];
        ctrl.event.momentDate = moment(ctrl.event.date, moment.ISO_8601, 'en');
    });

    // listen date changes (sync moment date with string date) 
    ctrl.onDateUpdate = function () {
        ctrl.event.date = ctrl.event.date = ctrl.event.momentDate.format(ctrl.dateFormat);
    };

    // submit updated event
    ctrl.onSubmit = function () {
        eventService.updateEvent(ctrl.event.id, ctrl.event.name, ctrl.event.date);
    };
}]);
```
```html
<div ng-controller="MyController as ctrl">
   <!-- ... -->
   <input moment-picker
          ng-model="ctrl.event.date"
          ng-model-options="{ updateOn: 'blur' }"
          format="ctrl.dateDormat">
</div>
```

Hope this helps, feel free to reopen this thread for any issue. :)
