### ISSUE TITLE
Format am/pm

### ISSUE THREAD

**Issue by mkharkovenko** [indrimuska/angular-moment-picker#135]
is it possible to make the hour picker into am/pm clock instead of 24-hr clock ?

**Comment by indrimuska** [comment]
Sure, you need to use momentPickerProvider, check it out in the README file.

**Comment by mkharkovenko** [comment]
Could you provide details? I used hours-format and hours-start/hours-end but it is not helped me

**Comment by indrimuska** [comment]
The option you're looking for is `hoursFormat`:

```javascript
angular
    .module('myApp', ['moment-picker'])
    .config(['momentPickerProvider', function (momentPickerProvider) {
        momentPickerProvider.options({
            hoursFormat: "hh:[00] A"
        });
    }]);
```

**Comment by mkharkovenko** [comment]
thanks
