### ISSUE TITLE
Sync selected date with model

### ISSUE THREAD

**Issue by is-bart** [indrimuska/angular-moment-picker#137]
I had a user ask me if it would be possible to not have to go through every view in the picker when editing a date. Right now I only get the date with the _change_ when the whole process is over but if they just wanted to change the month for instance they still have to click on the day, hour, minute, etc. even if these don't need changed.

Only way I see to get the current selection is with _selectable_ since I can extrapolate a value from the date and type parameters but that seems like a bad way to do it.

**Comment by indrimuska** [comment]
Hi @is-bart, as you said `selectable` is not the way to do that correctly, it's a dangerous method if you abuse it and I don't think it could be help you for that purpose.

I'm wondering why you can't simply use min/max view properties.

**Comment by is-bart** [comment]
Thanks for the reply @indrimuska

I don't understand how min/max view properties would be any help? 

The issue isn't that we don't need hour/minute/seconds views but that sometimes you might want to only change the month or only change the day and keep the hours/minutes/seconds. As it is right now a user has to go through every view even if they are not relevant. Eg: I want to keep an appointment at the same time but move it to the next day.

Thing is the model does not update until you have gone through every single allowed view. I assume that the directive has some internal variable that stores the current modified date and only updates the model with that date at the end. I was wondering if there is a way to access that date somehow or to update the model "live" and not just at the end when every view has been checked.

**Comment by indrimuska** [comment]
Ok @is-bart, now I figure out what is your use case.

Well, your analysis is correct, Angular Moment Picker stores two internal variables for the selected date in the picker that will be used to update the input after selecting the maximum allowed view. In your case you need a new property to keep in sync your model with the internal model of the picker.

I think this can be a nice feasible feature in the next days :)

**Comment by indrimuska** [comment]
Latest release [0.9.10](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.9.10) is now out with this feature! ;)
