### ISSUE TITLE
How to access minDate and maxDate in additions' templates 

### ISSUE THREAD

**Issue by mouss-delta** [indrimuska/angular-moment-picker#138]
How can I access minDate and maxDate in additions' templates? In the sample you give in plunker you use ng-template to define the additions :

```html
<script type="text/ng-template" id="top-template-url">
    <div class="text-center alert alert-info">
        Select your birthday date
    </div>
</script>
``` 

And I would like to use the top addition to display a message to say the autorized date (set with min-date and max-date attributes), however I didn't manage to access minDate and maxDate from the ng-template.

**Comment by indrimuska** [comment]
Hi @mouss-delta, you can access to the internal directive scope, but it's not a good thing to do.
Let me change the code in order to transclude the same scope you have in your input.

**Comment by indrimuska** [comment]
This will be available in the next release.

**Comment by mouss-delta** [comment]
Thanx a lot @indrimuska

**Comment by indrimuska** [comment]
Latest release [v0.9.8](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.9.8) is now out.

**Comment by indrimuska** [comment]
@mouss-delta I've added a sample in README to help you.

**Comment by mouss-delta** [comment]
@indrimuska I am sorry I am not finding the paragraph with the sample, can you please tell me which paragraph to look? I have tried also the plunker that deals with additions attribute but didn't find the code to help using this feature

**Comment by indrimuska** [comment]
Check out the "additions" parameter under the [Options section](https://github.com/indrimuska/angular-moment-picker#options).
https://embed.plnkr.co/CXOH5U
