### ISSUE TITLE
Memory Leak using moment-picker

### ISSUE THREAD

**Issue by Swati16T** [indrimuska/angular-moment-picker#139]
I am using this component in my angular app. On every new page, i am inserting a new date time component.
After opening 20 pages (not simultaneously), my app becomes slow and less responsive and a tremendous amount of memory leaks is seen.
After removing just this component, things were smooth again.
Is there some thing i am missing while using this js?

Attaching a snippet from my code.
[Date-time-picker-template.zip](https://github.com/indrimuska/angular-moment-picker/files/824300/Date-time-picker-template.zip)

**Comment by indrimuska** [comment]
Hi @Swati16T, thank you for reporting this. I'll look at this in the next days.
I'm sorry I don't have too much spare time in this period. :(

**Comment by indrimuska** [comment]
Well @Swati16T, in the attached zip file I just see this piece of code:

```html
<div class="input-group" 
     moment-picker="mymodel"
     format="YYYY-MM-DD">
  <span>
    <i class="octicon octicon-calendar"></i>
  </span>
  <input class="form-control"
         placeholder="Select a date"
         ng-model="mymodel"
         ng-model-options="{ updateOn: 'blur' }">
</div>
```

Well, this not helps very much to investigate why your app becomes slow.
Could you please provide (here or on a private chat on [Gitter](https://gitter.im/indrimuska)) a full working example that shows your issue?
Thanks :)

**Comment by F0r3v4R** [comment]
I'm seeing a Window leak that appears to be stemming from the handler attachment of $scope.view.position() to 'resize scroll'.  

angular-moment-picker.js:792 angular.element($window).on('resize scroll', $scope.view.position);

When Window is destroyed, these are not removed (off).  Not sure if this is related or a different issue.

**Comment by indrimuska** [comment]
Thanks @F0r3v4R for the tip, it will be part of the next release.
Anyway I'm going to close this issue, feel free to reopen it again for any other problem. :)
