### ISSUE TITLE
Add the capability to disable

### ISSUE THREAD

**Issue by ccollie** [indrimuska/angular-moment-picker#14]
As in title.

**Comment by indrimuska** [comment]
Hi @ccollie, I think this could be a useful feature. Are you interested in creating a PR?

**Comment by ccollie** [comment]
Give me a hint and I can probably find the time to look at it.

**Comment by indrimuska** [comment]
Maybe the simplest way to do this is to avoid opening the picker dialog and prevent the update from the view value (this second check is not so easy to explain, if you're interested I could give you more infos about Moment Picker internal variables).

**Comment by ccollie** [comment]
I'll take a look over the weekend.

2016-02-18 7:25 GMT-05:00 indrimuska <notifications@github.com>:

**Comment by indrimuska** [comment]
This is now out with [v0.4.0](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.4.0). :)

**Comment by ccollie** [comment]
Many thanks !
