### ISSUE TITLE
Moment-Picker not displaying dates via ng-model

### ISSUE THREAD

**Issue by luludpsalmist** [indrimuska/angular-moment-picker#140]
So i've added on the moment picker and I'm able to access the datepicker  by simply clicking to select dates. It is not exactly clear to me however as to how I can get the date pre-populated. 

I have added my date to the input by simply using ng-model  directive
<input type="text" class="form-control input-sm" moment-picker="vm..FromDate" ng-model-options="{ updateOn: 'blur' }" ng-model=" vm.FromDate" />

Perhaps There is something I'm missing ? 
Another issue I noticed is that even when I select a date and submit it as part of a form , i seem to get the ""(apostrophes) posted as well which results in  an error.

**Comment by Yugloocamai** [comment]
Same issue here.

**Comment by indrimuska** [comment]
Hi @luludpsalmist, I am not sure I've completely understood your problem.
Could you kindly post a working plunker that shows your issue?
Many thanks.

**Comment by dtkern** [comment]
I have the same problem. Trying to set today date as default but I can't get the input to show ng-model value.

**Comment by indrimuska** [comment]
Hi @dtkern, are you able to reproduce this in working example I can look at?

**Comment by dtkern** [comment]
@indrimuska, I got it working, thanks. I created a plunker anyway so other developers can see it working.
https://plnkr.co/edit/Ytpur67FOsRX41nMBFPL?p=preview

The problem was I had an old version of angular-moment-picker. After upgrading to the latest version everything worked fine.

**Comment by luludpsalmist** [comment]
hi @indrimuska  sorry for the late reply. Following on from @dtkern 's plunker I think what I missed was that I needed to retrieve date like this 'vm.fromDate = moment()' in the controller otherwise model dates don't display. 
The second issue I get is that i have "" around dates when I submit the form i.e 
fromDate=%222017-03-17T13:26:40.217Z%22  . you can see the encoded strings around dates .Is there a way to get the date in this format fromDate=2017-03-17 on submit ?

**Comment by indrimuska** [comment]
Sure @luludpsalmist, if you use two different properties for `ng-model` and `moment-picker` you'll see that (as show in README):
 - `ng-model` handles the Moment.js date object
 - `moment-picker` handles formatted date string

Otherwise you can just format your moment date like this:

```js
var formattedDate = ctrl.momentDate.format('YYYY-MM-DD');
```
