### ISSUE TITLE
Moment picker doesn't update input field

### ISSUE THREAD

**Issue by cbranca** [indrimuska/angular-moment-picker#141]
I'm using angular moment picker with angular material. When I pick a date it doesn't appear in the input element. This is the code that doesn't work:
```
<md-input-container>		
    <input ng-model="vm.toTime">						
</md-input-container>
<md-icon md-svg-icon="time" moment-picker="vm.toTime" format="HH:mm"></md-icon>				
```

If I put the moment-picker directive inside the input element it works. But I want to show the picker if I click on the icon, not on the input field. I'm missing something?

**Comment by mouss-delta** [comment]
Hi, I had similar issue you have to combine moment-picker and ng-model directives. Have a look here : https://plnkr.co/edit/P6F158?p=preview

**Comment by indrimuska** [comment]
Hi @cbranca, your code should work, which version are you using?

[Check out this plunker.](https://plnkr.co/edit/qRoYTI?p=preview).

**Comment by indrimuska** [comment]
I hope the plunker helped you, I'm going to close this issue.
