### ISSUE TITLE
How to initialise only time and not date

### ISSUE THREAD

**Issue by mouss-delta** [indrimuska/angular-moment-picker#142]
I am using the picker with the following format : "DD.MM.YYYY HH:mm", and I am using start-date property to set the initiale date of my date picker. 

I am in the case where I want to give initial value only for the hour and not the date, for example I would like the time 10:30 to be preselected but the rest (year, month, view) has to be selected by the user. I tried start-date="10:30" even if the format is "DD.MM.YYYY HH:mm", it didn't work. I have also tried start-date="DD.MM.YYYY 10:30" it also didn't work.

My question is : is this feasible? If yes how can I make it work? If not, would it be possible to consider this request as enhancement?

Thanx in advance

**Comment by indrimuska** [comment]
Hi @mouss-delta, this is a strange but interesting use case.

You say that users have to change the year/month/day and the hours/minutes should be preselected. But when someone opens the picker an year/month/day should be presented. And here it's the point: which one year/month/day should be presented? Why should not simply preselect all?

**Comment by mouss-delta** [comment]
Hi @indrimuska,

Thank you for your update. 

I admit that this use case is strange, I am working on an event scheduler application, and in fact I need this feature when users duplicate an event, when users duplicate an event they would like to give only the date (=day/month/year) and the hour (=hour:minute) to be pre-selected.

My answer to : "which one year/month/day should be presented", it would be year.
My answer to : "Why should not simply preselect all", because with my use case the user would have to change de date (=day/month/year), so preselect all offers nothing to users.

**Comment by indrimuska** [comment]
Can you simply disable hour/minute views when dates are cloned?
Checkout this plunker: https://plnkr.co/edit/iwQZp7alnROivBpEyK95?p=preview

**Comment by indrimuska** [comment]
I'll close this issue. Feel free to reopen it if that plunker does not fit your needs.
