### ISSUE TITLE
Open at specific month

### ISSUE THREAD

**Issue by pedrokost** [indrimuska/angular-moment-picker#144]
I use this library as a date range picker. When user select the "from" date much in the past (say 5 months ago), I would like the "to" picker to open at the same month as the "from" value. Currently, the default view shows the current month.

Is this possible?

**Comment by indrimuska** [comment]
Hi @pedrokost, this is actually possible because the directive does not listen updates on `stat-date`. Anyway this could be an interesting feature!

**Comment by indrimuska** [comment]
Done! This will be available in the next release, a plunker will follow.

**Comment by indrimuska** [comment]
Latest release [v0.9.8](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.9.8) is now out.

**Comment by indrimuska** [comment]
[Check this sample out.](https://embed.plnkr.co/GtOkThfKwSQ4aPbZYLMw)

**Comment by pedrokost** [comment]
@indrimuska Fantastic!
