### ISSUE TITLE
Displaying current time [breakdown minutes]

### ISSUE THREAD

**Issue by AlexandreLogist** [indrimuska/angular-moment-picker#147]
Hello Guys,

```
            today:         true,
            locale:         'nl',
            minView:       'year',
            maxView:       'day',
            minutesStep:   60,
            secondsStep:   60,
            format:        'L LT',
            hoursFormat:   'HH:[00]'
```

I can select until the hours (no minutes): 1:00 - 24:00, but when it's selected the minutes are the minutes that are on my computer... What am I missing? :) Thanks in adv !

**Comment by indrimuska** [comment]
Hi @AlexandreLogist, what do you mean with *the minutes are the minutes that are on my computer*?
Could please further argue your problem?

**Comment by AlexandreLogist** [comment]
Hé,

when I select a datetime from the picker, until the hour -> so no minutes select, the picker takes the minute value from my computer/server...

**Comment by indrimuska** [comment]
It depends on how you've set the picker. Could you please post a full working example showing your issue? Thanks.

**Comment by indrimuska** [comment]
I'll close this issue since no answers were provided.
