### ISSUE TITLE
Dynamic positioning breaks on iPad with keyboard

### ISSUE THREAD

**Issue by pedrokost** [indrimuska/angular-moment-picker#148]
The positioning of the datepicker does not take into account the on-screen keyboard. In the screenshot below it is possible to scroll up to see the picker, but if the picker where at the very bottom of the page (e.g. fixed at bottom), the picker would be inaccessible. Instead of positioning itself on top of the element, it displays below it, and the keyboard covers it.

I would be fine with manual positioning in this case.

![img_0025](https://cloud.githubusercontent.com/assets/725286/23897610/18a30ab8-08ae-11e7-9b48-2096e38bac02.PNG)

**Comment by rahultokase** [comment]
Hi 

I am facing the same issues do you have any workaround for this

**Comment by indrimuska** [comment]
Hi guys, I'll work to give you a property to allow choosing a fixed placement of the picker.
In the meantime you can add the `readonly` attibute to your `<input>`s to avoid opening the keyboard.

**Comment by pedrokost** [comment]
@indrimuska Thanks, that's a good enough workaround for me. Manual input is not possible anyway.

**Comment by indrimuska** [comment]
Latest release [v0.9.8](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.9.8) is now out.
