### ISSUE TITLE
Add an on-change event

### ISSUE THREAD

**Issue by ccollie** [indrimuska/angular-moment-picker#15]
I'm implementing a date range control, and as it stands, i need to create a watch to
ensure the start date is less than the end date. Looking at the source, it would be straightforward to support an on-change event so the user does not have to resort to 
additional watches.

**Comment by indrimuska** [comment]
You're right, this is a very easy-to-implement feature.
Thank you man for interesting in angular moment picker, I will work into this in the next days. :)

**Comment by indrimuska** [comment]
FYI this feature is now available in the last release! :)

**Comment by ccollie** [comment]
Nice !! Thank you for the effort !

2016-02-22 9:15 GMT-05:00 indrimuska <notifications@github.com>:
