### ISSUE TITLE
Feature: inline picker

### ISSUE THREAD

**Issue by miguelalche** [indrimuska/angular-moment-picker#151]
Hello friends! 
Thanks for this amazing package! 

I just wanted to know if there was a better way to display the picker calendar as an element that doesnt go away. I've tried hacky css styles but I don't like very much the result! 

Thanks! 

Mike

**Comment by indrimuska** [comment]
Hi @miguelalche, I think it would be useful to have an inline calendar, even if changing the view after selection could be quite annoying.

Anyway this sounds like an easy to code feature, stay tuned. :)

**Comment by miguelalche** [comment]
Hi @indrimuska  that would be amazing!!

let me expand
Right now I only managed to disable the "position:absolute" so i have this: 
![c4yhxacg p daaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/8585011/24064566/ef8bbd26-0b43-11e7-8392-351451598378.png)

but I can't get rid of the input that I marked with red.  Also if I click away the calendar closes. 
I managed to get just the calendar also by passing format="DD" in the directive, but it also doesn't feel very good. 

I'm quite a beginner, but if I can help with something please tell me! 

Thanks!

**Comment by indrimuska** [comment]
Well the picker closes because of the directive `ng-show` that hides the picker after selection.
At the moment you can force displaying the picker every time by setting this rule:

```css
.moment-picker-container {
    display: block !important;
}
```

**Comment by indrimuska** [comment]
Latest release [v0.9.8](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.9.8) is now out.

**Comment by miguelalche** [comment]
you are amazing!!! thanks!!!
