### ISSUE TITLE
Display current date

### ISSUE THREAD

**Issue by rohith612** [indrimuska/angular-moment-picker#152]
hey,
      How to display current date in the input control by default
      <input class="form-control"
             placeholder="Select a date..."
             moment-picker="ctrl.input.stringDate"
             locale="en"
             format="YYYY-MM-DD"
             ng-model="ctrl.input.momentDate"
             ng-model-options="{ updateOn: 'blur' }">

**Comment by clinm** [comment]
Hi,

You should take a look at the [existing Plunker](https://embed.plnkr.co/hs10SM), especially the **setToday** method  in the script.js file, it should give you what you need.

**Comment by rohith612** [comment]
Fine it works.... Thank you...
