### ISSUE TITLE
Locale not working...

### ISSUE THREAD

**Issue by Chukatuk** [indrimuska/angular-moment-picker#153]
Hi, i'm using the Fuse Angular admin theme, and i am unable to switch the picker language.
I started working with the picker by adding it in the HTML:
`<div start-view="day" format="DD/MM/YYYY" moment-picker="student.Birthday" >`
I added:
` locale="he"`
The language remained English.

Later i decided to try and make it global, so i added:
```
angular
    .module('fuse', ['moment-picker'])
    .config(['momentPickerProvider', function (momentPickerProvider) {
        momentPickerProvider.options({
            locale: "he"
        });
    }]);
```
(Its not exactly the code, i didn't want to paste the entire thing.)

When i call the provider from console,
`var serv = angular.element(document.body).injector().get('momentPicker')
`
i can see other options and that the locale is set to "he", but the the picker is still in English...

I tried to find any picker related settings in the theme, i didn't find anything.

Don't know if its related, but i get the following message in the console (any language and without the settings):
```
TypeError: Cannot read property 'preparse' of null
    at prepareConfig (moment.js:2415)
    at createFromConfig (moment.js:2394)
    at createLocalOrUTC (moment.js:2481)
    at createLocal (moment.js:2485)
    at hooks (moment.js:16)
```

Thank you!

**Comment by clinm** [comment]
Hi !

You didn't specify what files you are including in your HTML file so I'll give this solution a shot :

You may not have included the correct *moment.js* file. You need the one called 'moment-with-locales'.
As you can see in [this example](https://plnkr.co/edit/iTZksLB4IX80iR81d4uu?p=preview), it works with locales and put the english version as default if moment.js is included.

The correct files are : 
```
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.4.4/angular.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment-with-locales.js"></script>
<script src="//cdn.rawgit.com/indrimuska/angular-moment-picker/master/dist/angular-moment-picker.min.js"></script>

```

**Comment by Chukatuk** [comment]
Hi,
I installed the package with Bower, so i thought that it will be included...
Added the locale manually.
Sorry, i'm new to this stuff, thank you @clinm !

**Comment by clinm** [comment]
You're welcome !

You can find moment with locales here with bower *bower_components/moment/min*

**Comment by rvvpatel** [comment]
Hi clinm please help me how to solve this problem. i using angularjs 1.5.9
