### ISSUE TITLE
Disable selected date !

### ISSUE THREAD

**Issue by rohith612** [indrimuska/angular-moment-picker#154]
hey,
        Is it possible to disable selected date in the picker , and how.
        I got some date from database and i need to disable it  in the picker ?

**Comment by clinm** [comment]
Hi !
Did you take a look at [this example](https://github.com/indrimuska/angular-moment-picker#methods) ?

**Comment by rohith612** [comment]
yup !
but it work for single date only ?
i need to disable multiple dates which stored from the database
if once the page loads i need to disable selected date from the picker
and somehow /selectable="ctrl.isSelectable(date, type)"/ have higher priority than others

**Comment by rohith612** [comment]
hey , 
i got it ... in my try

**Comment by clinm** [comment]
I understand you achieved what you wanted to do ?

**Comment by rohith612** [comment]
i need a page of information include a picker , bt some dates(previously selected) are do not selected by another page transaction ,
so the selected date are in the database. when the page loads date from the db will disable from the picker.

**Comment by indrimuska** [comment]
I don't think I've understood your problem @rohitbind. Which pages are you referring to? Can you please post a sample for your issue? Thanks.

**Comment by rohith612** [comment]
fine . i got the solution thanks.

**Comment by indrimuska** [comment]
Good, happy to hear that! :)
