### ISSUE TITLE
Initialization suggestion

### ISSUE THREAD

**Issue by roberteles** [indrimuska/angular-moment-picker#155]
Hello @indrimuska ,

Thanks for this fantastic date picker - I feel it's one of the best ones out there.

To offer you a little bit of context, I believe that most people developing applications prefer keeping one standard regarding time, which is the ISO8601 format (eg. 1980-12-20T00:00:00.000Z). There are many libraries out there which can format this for viewing purposes, hence the popularity of it.

I think that the expectation of many of my other fellow colleagues, including mine, is that when they pass a variable to your date picker, they expect it to be read automatically, and then display it in the format specified, but still keeping the actual model data in the initial ISO8601 way.

For example, if vm.dob = 1980-12-20T00:00:00.000Z, then <input moment-picker="vm.dob" format="MM-DD-YYYY"> should display the data as 12-20-1980, without having to manually format the string variable in the controller, or set the vm.dobModel to be equal to moment(). Then, when one would check vm.dob after the date-picker loaded, it would still be 1980-12-20T00:00:00.000Z.

The ultimate goal with this is to be able to control the format the data is displayed, while the model/data in itself maintains the ISO8601 format, and when sending that data back to the server, there is no extra formatting that needs to be done.

I believe that this works automatically with the 'YYYY-MM-DD' format, but I can confirm that it is not working with 'MM-DD-YYYY', since moment.js doesn't know how to pick it up, and it forces us to pre-format the text to MM-DD-YYYY, pass it to moment-picker and then reformat it to ISO8601 before sending it to the API, which is a cumbersome experience, it involves adding more code to controllers, when I think it can be nicely solved in the component.

Best,
Robert

**Comment by indrimuska** [comment]
Hello Robert,
Many thanks for the kind words.

Your request seems reasonable, but there are few points I need to figure out before.

 1. You say that a lot of code should be performed in the controller to do that, but it just require 2 conversions from and to Moment.js object:

    ```javascript
    app.controller('MyController', [function () {
        var ctrl = this;

        // convert ISO string -> Moment object
        this.date = moment('1980-12-20T00:00:00.000Z', moment.ISO_8601);

        this.onSubmit = function () {
            // convert Moment object -> ISO string
            var date = this.date.format(moment.ISO_8601);
        };
    }]);
    ```
    ```html
    <div ng-controller="MyController as ctrl">
        <input moment-picker ng-model="ctrl.date" format="MM/DD/YYYY">
    </div>
    ```

    1.1 Since [ISO 8601 is natively supported by Moment.js](https://momentjs.com/docs/#/parsing/special-formats/) you can even simply use moment constructor and format methods without having to pass the format string.

    ```javascript
    // ISO string -> Moment object
    this.date = moment('1980-12-20T00:00:00.000Z');
    // convert Moment object -> ISO string
    var date = this.date.format();
    ```

 2. Actually the directive have the `moment-picker` property to handle with formatted date string, in the format given by `format` property, and the `ng-model` property to handle with Moment.js objects. How do you think people should use this feature? Do we need to add a third model for the ISO date string? And if they need a different format that is not the standard ISO 8601, do we a new property for that?

 3. Do you really think that keep in sync 3 different models is more easy than the two lines of code at point 1.1? Would you like to propose a PR for that?

Sorry for the long answer :)
Thanks.

**Comment by indrimuska** [comment]
I'll close this for now, but feel free to continue the discussion if you like :)

**Comment by ayepiz** [comment]
Just a though here, can the directive initialization convert the ngModel to a moment type in case I supply a string?

The thing is, I have dynamic forms where I bind directly from the backend (json) to the input models without adding any custom logic in the middle of that. Because of this, I can't convert to moment the ISO string that comes from the server.
