### ISSUE TITLE
get view

### ISSUE THREAD

**Issue by diegofcoelho** [indrimuska/angular-moment-picker#156]
Is there a way to get the current view the user is using (Year/month/day)?

**Comment by indrimuska** [comment]
Hi @diegofcoelho,
Actually there's no method to do that. Can you please provide more context to figure out why you need this feature?

**Comment by diegofcoelho** [comment]
I need to add some restriction to date selection in a scheduling like app and user will only be allowed to pick a date if it is at least three hour, in the future, from now.

Angular moment picker has a function that disable previous dates and that is what I need, except that a glitch appears when a day is still partially allowed.

Lets say I want to book a date today and now is already 16h and that angular-moment-picker is with a date_now+3h restriction applied. The page should allow me to book anything from 19h. However, when we are in a (week?) view the day's date is shown as enable until the moment you hover it. At his point it fades, you can't click it, and thus isn't possible to book anything for today...

By knowing the view the user is accessing at the moment we could fix this behaviour.

Can you understand or I did make it too complicated trying to explain?

**Comment by indrimuska** [comment]
I think I've understood the problem, but in any case are you able to provide a plunker so that I can try to fix it for your exact use case? Thanks.

**Comment by diegofcoelho** [comment]
I've never used plunker before so please forgive any silly thing I've done:

https://plnkr.co/edit/RxzIoX6Wn5SaTXLyMwGk

Try to select the same day we are and you will see what I've described.

**Comment by indrimuska** [comment]
The problem here is in the `isSelectable` callback, in particular:

```js
    if (date.date() == $scope.minDate.date()) {
        if (date.hour() >= $scope.minDate.hour()) {
            // ...
```

As you can see, you are checking the hour of a single Day in the Month View. But in Month View hours are not set, you should just check given Date (day) in that view.

Anyway, for your use case there is a more fitting property property called `minDate` and you should use it instead of `isSelectable`. Check out README file for more information.
