### ISSUE TITLE
Dynamic value for format attribute

### ISSUE THREAD

**Issue by mcoul** [indrimuska/angular-moment-picker#157]
Hi, @indrimuska!
I've started using angular-moment-picker a couple of days ago, it's a really nice package, plus i find it easy to use. However, I've been struggling with asigning a dynamic value to the format attribute depending on what the user chooses, instead of a fixed "YYYY-MM-DD" string, for example. 
Is there a dynamic way to set the format value?

In the html I have:
`<input class="form-control" moment-picker="dateString" format="dateSelected.format" ng-model="dateObject" ng-model-options="{ updateOn: 'blur' }">`

If I output the {{ dateSelected.format }} expression, I can see that the string is correctly binded in my view, but it doesn't seem to be recognized as a string by the format attribute (which only accepts strings as values).

dateSelected is an object (previously selected by the user) from the following array:
`$scope.typesOfDates = [
            {
                type: 'day',
                format: 'YYYY-MM-DD'
            },
            {
                type: 'month',
                format: 'YYYY-MM'
            },
            {
                type: 'year',
                format: 'YYYY'
            }
        ];`

Thanks for reading.
Regards,
Micaela.

**Comment by indrimuska** [comment]
Hi @mcoul, thanks for the kind words.

It should be already possible to use dynamic format value, you just have to keep in mind that the property is binded with "@", so it expects a string as input. In that case, you can simple try to surround your scope property with double curly brackets:

```html
<input class="form-control"
       moment-picker="dateString"
       format="{{dateSelected.format}}"
       ng-model="dateObject"
       ng-model-options="{ updateOn: 'blur' }">
```

**Comment by mcoul** [comment]
Hi @indrimuska , thanks for the fast answer. I've already tried using:
format="dateSelected.format"
format="{{dateSelected.format}}"
format="'{{dateSelected.format}}'"
format="'{{::dateSelected.format}}'"

None of them seem to work, the calendar will ignore this value (not recognize it as a string) and let me select year->month->day->hour->minute, etc.

**Comment by indrimuska** [comment]
Check out this [plunker](https://plnkr.co/edit/qDPesI?p=preview).

**Comment by mcoul** [comment]
I've made a few changes based on your plunker and now it works like a charm, thank you! I think the issue was because I didn't use "var ctrl = this;', I just used every variable accessing the $scope. Now that I access them like you do, it works as expected.

**Comment by chaluvadis** [comment]
how can I disable time selection dynamically, currently i have a scenario where user select date time in one case, in another case user selects only date.

`<div class='input-group date-border' start-view="{{startView}}" format="{{format}}" moment-picker="event.end">
                            <input type="text" readonly required name="end" id="end" class="form-control ssi-form-control"
                                placeholder="Event End Date" data-ng-model="event.end" style="border:none;">
                            <span for="startDate" class="input-group-addon span-date-picker" style="border:none;">
                                    <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>`

where startView  = 'month', format = 'MM/DD/YYYY hh:mm A' and 'MM/DD/YYYY'.

Dynamically I am setting the format value, when i observe the DOM I am able to see the changes but the date picker is still showing the time selection.

The plunker u shared above is also have the same issue.
