### ISSUE TITLE
jQuery compatibility

### ISSUE THREAD

**Issue by easyest** [indrimuska/angular-moment-picker#158]
If jQuery is loaded, then it is not possible to enter date by keyboard into an input. Plunker here:
https://plnkr.co/edit/hs10SM?p=preview

It would seem the problem is with the code:
`.on('keydown', function (e) { return $scope.keyboard && $scope.$evalAsync(function () { return $scope.view.keydown(e); }); });`

jQuery documentation mentions that:
> Returning **false** from an event handler will automatically call event.stopPropagation() and event.preventDefault(). A false value can also be passed for the handler as a shorthand for function(){ return false; }. So, $( "a.disabled" ).on( "click", false ); attaches an event handler to all links with class "disabled" that prevents them from being followed when they are clicked and also stops the event from bubbling.

**Comment by easyest** [comment]
I fixed the problem by changing the code from:
```
.on('keydown', function (e) { return $scope.keyboard && $scope.$evalAsync(function () { return $scope.view.keydown(e); }); });
```

to:
```
.on('keydown', function (e) {
	if ($scope.keyboard) {
		return $scope.$evalAsync(function() { return $scope.view.keydown(e); });
	} else {
		return true;
	}
});
```

**Comment by indrimuska** [comment]
Thank you @easyest, this fix will be available in the next release!

**Comment by easyest** [comment]
Many thanks :)

**Comment by cvuorinen** [comment]
I ran into this same issue and was just about to make a pull request and noticed it was already fixed in master.

Any info when next release might be tagged?

**Comment by indrimuska** [comment]
Hi @cvuorinen, I'll release next version next Tuesday.
