### ISSUE TITLE
Min. version of Angular?

### ISSUE THREAD

**Issue by hemraker** [indrimuska/angular-moment-picker#159]
Hey there, this looks pretty awesome!

Is there a minimum version of Angular required to use this?

**Comment by indrimuska** [comment]
Hi @hemraker, the directive has been tested starting from Angular version 1.3 so far, but if you need lower versions and you find any problem feel free to open an issue here on github. :)

**Comment by hemraker** [comment]
Unfortunately, I'm working with Angular version 1.1.5, so will most likely run into issues. Are you saying you're up for supporting lower versions ? 😄

**Comment by hemraker** [comment]
And thanks a bunch for the quick response @indrimuska !!

**Comment by hemraker** [comment]
Haha, I wish simply thinking about it would do it!

Had a go at creating a date picker editor for [Umbraco CMS](https://github.com/umbraco/Umbraco-CMS). Installation and initialization was a breeze but there indeed dependencies that are not available in 1.1.5. I will create an issue for it and let you be the judge 😄 

Really awesome work by the way 🙌

**Comment by hemraker** [comment]
Closing this and create issue for backwards compatability
