### ISSUE TITLE
Allow manual date input

### ISSUE THREAD

**Issue by manufaktor** [indrimuska/angular-moment-picker#16]
I would like to allow manually typing the date into the input.
Currently it completes the date after the first key stroke using the typed number as value for whatever is the first unit for the chosen date format. Example: my format is YYYY-MM-DD, I press "5" and it completes to "0005-01-01".

Is this something you'd consider adding/accepting in to the library?

**Comment by indrimuska** [comment]
Hi @manufaktor, Angular Moment Picker could be anywhere you like, including text inputs.
Since it makes use of angular `$watch`es to track model changes, if you append the picker to a text input and you want to type a date manually, you should use [ng-model-options](https://docs.angularjs.org/api/ng/directive/ngModelOptions) like this:
```html
<input moment-picker="myDate" ng-model="myDate" ng-model-options="{ updateOn: 'blur' }">
```

**Comment by manufaktor** [comment]
Thanks, perfect!

**Comment by indrimuska** [comment]
Glad to see you've solved this issue!
Maybe I will add this behavior to the demo page too.. :)

**Comment by usman45** [comment]
Hey.
Really good job done in Angular Moment Picker.

I might have found issue related to using ng-model-options="{ updateOn: 'blur' }. When clicking the input field the very first time, element's value is empty(undefined) even though I did input the date string. However when clicked the second time then the elements value appears. This breaks somehow the immediate validation. 

When I remove ng-model-options then it works fine but then I can not inout date manually. Hope you got the point. Thanks!

**Comment by webironmac** [comment]
I confirm this bug exists. Same problem here.
