### ISSUE TITLE
change event not working since 0.9.4

### ISSUE THREAD

**Issue by wellcaffeinated** [indrimuska/angular-moment-picker#160]
I've got a datepicker that's using the change event and after upgrading to 0.9.10 the event isn't triggered
```pug
// pug template
.input-group(
        moment-picker="time",
        format="{{timeFormat}}",
        change="update()")
// ...
```

**Comment by indrimuska** [comment]
Hi @wellcaffeinated, have you check out this [plunker](https://embed.plnkr.co/IIhjjv)?

**Comment by kalle17** [comment]
Hi
It looks like "change" event works fine with controller functions in "controller as" mode, but it doesn't work with scope-defined functions.

**Comment by indrimuska** [comment]
This sounds like a typical scope-shadow issue, that's why you should use dot-notation.
Read more here: https://github.com/angular/angular.js/wiki/Understanding-Scopes

**Comment by wellcaffeinated** [comment]
But the thing is it works just fine in earlier versions. So it's a problem
with the new version...
