### ISSUE TITLE
Backwards compatability for < Angular 1.2

### ISSUE THREAD

**Issue by hemraker** [indrimuska/angular-moment-picker#161]
The use of $sce prohibits implementing this fine date picker in Angular versions prior to 1.2.

Initializing the module fails with: `Error: Unknown provider: $sceProvider <- $sce <- momentPickerDirective`

**Comment by indrimuska** [comment]
Hi @hemraker, I found a LOT of different properties with Angular 1.2 (e.g. missing `$watchGroup`, `$commitViewValue`, ..). For that reason I think that this directive won't support Angular < 1.2.
I'm sorry! :(
