### ISSUE TITLE
start-date highlight.

### ISSUE THREAD

**Issue by whittssg** [indrimuska/angular-moment-picker#164]
Hello,

When i provide a start date shouldn't the calendar highlight the selected dates /times?
(not sure if its just not working or if it just doesn't do this)
Thanks ( am using inline)

**Comment by whittssg** [comment]
Never mind.. I think its because i give the time as now so the minutes dont match the intervals. Date and hours highlighting works fine.

**Comment by whittssg** [comment]
The inline option is really neat BTW.. I didnt want to use any other library because they didnt match the angular material inputs that i use else where but being inline gets rid of that. Thumbs up to an awesome library. Thanks

**Comment by DrakeXiang** [comment]
How did you solve this? Even official demo can't initialize date using this directive https://embed.plnkr.co/rjFk9d
