### ISSUE TITLE
Select Time without Date

### ISSUE THREAD

**Issue by Vishal2060** [indrimuska/angular-moment-picker#166]
How we can select time irrespective of date.

If I choose time picker, it shows Date on its header.
![screenshot from 2017-04-28 11-43-30](https://cloud.githubusercontent.com/assets/27874723/25516464/64a075b8-2c08-11e7-8dc6-f07cd38b4880.png)

**Comment by indrimuska** [comment]
Hi @Vishal2060, if you set `format` to anything that not includes years, months or days than you can choose one of these options:

 - Change the model date programmatically: using the Moment.js object you can perform any operation on date
 - Hide the header bar: by setting `show-header="false"`

Hope this helps :)
