### ISSUE TITLE
Calendar doesn't render correctly if model value is change programmatically

### ISSUE THREAD

**Issue by michaelandrew** [indrimuska/angular-moment-picker#17]
If the model value is changed programmatically at some point after the directive has first been loaded, the calendar will not render and thus the wrong month will be selected.

![image](https://cloud.githubusercontent.com/assets/1167544/13576661/aeddad78-e486-11e5-877c-56bb09d54f47.png)

This is caused by [angular-moment-picker.js#L446](https://github.com/indrimuska/angular-moment-picker/blob/master/dist/angular-moment-picker.js#L446)

If the model value has been changed programmatically, the watch on model will fire which in turn causes this watch to fire, but newValue and oldValue will always be the same in this case, and thus it won't render.

**Comment by indrimuska** [comment]
Hi @michaelandrew, thank you for reporting this.
I verified the bug, give me five to resolve it. ;)

**Comment by indrimuska** [comment]
This should be fixed in the latest release.
Waiting for your feedback!

**Comment by michaelandrew** [comment]
Perfect! Thanks!
