### ISSUE TITLE
Failed to instantiate module moment-picker

### ISSUE THREAD

**Issue by dkrychylskyy** [indrimuska/angular-moment-picker#171]
Hello,
I'm new in angular)))
For Ionic v1 I installed angular-moment-picker
`bower install moment-picker --save`,
there is a directory `bower_components` with `angular-moment-picker`,
I added '`moment-picker'` in `angular.module([])`
RESULT: 
![capture d ecran 2017-05-05 a 19 26 14](https://cloud.githubusercontent.com/assets/27224802/25756894/c3861202-31c8-11e7-8695-3d500db64f4a.png)

What am I doing wrong? Why I have a errors?
Thank you all

**Comment by indrimuska** [comment]
Hi @dkrychylskyy, could you please create a simple plunker/fiddle/codepen to analyze this issue?
