### ISSUE TITLE
Show picket inline instead of in popup

### ISSUE THREAD

**Issue by pedrokost** [indrimuska/angular-moment-picker#172]
Feature request: to be able to show the date picker inline, instead of in a popup. So, instead of having an input field which on click opens a popup, I just want to display the picker without previous user action.

Example from [uiBootstrap](https://angular-ui.github.io/bootstrap/)
![image](https://cloud.githubusercontent.com/assets/725286/25774412/67fd3f2a-328e-11e7-8c19-4da3bb4a9a9e.png)

**Comment by indrimuska** [comment]
Hi @pedrokost, if you check out in the [README](https://github.com/indrimuska/angular-moment-picker#options) file this is already available by adding the `inline="true"` property ([plunker](https://embed.plnkr.co/5PhKOc)). My advise is to use it in addition with the `set-on-select` property.
