### ISSUE TITLE
Getting another type of picker instead the one shown in the demo page

### ISSUE THREAD

**Issue by Bartaf83** [indrimuska/angular-moment-picker#179]
Hi, 
When i click on the cell to edit the date the first time, i'm getting [this indesirable picker](http://i.imgur.com/nBvYWPC.png) instead the one shown in the demo page.

How i can get rid of it and get this one and get back the other picker as in the demo?

the htlm tag looks like this 

`<div moment-picker="row.entity.values[\'' + col.id + '\'].value" format="MMM Do YYYY" min-view="year" max-view="month" start-view="month" autoclose="true" today="true" keyboard="true"> {{ grid.appScope.formatMe(grid.getCellValue(row, col), col.colDef.year) || \'Click here to select a date\' }} </div>`

Cheers

**Comment by indrimuska** [comment]
Hi @Bartaf83, this is because you are using input with `type="date"`, so the every browser uses its own implementation of a date input. To avoid this, you just need to set input type to `text` or just remove the type property (so that the browser fallback to text type).

**Comment by Bartaf83** [comment]
Thanks ! i will try that but as you see i'm not using the tag with the input (but now i ll try to use it and change its type to text)

**Comment by indrimuska** [comment]
Mmm, it quite impossible that the template you've sent will open the classic browser calendar.
Also, `<div>` tag is not editable, but in the screenshot you have the focus on a field!

**Comment by Bartaf83** [comment]
i'm using the datepicker inside the angular ui grid , that's why there is the focus

**Comment by indrimuska** [comment]
So, you have to handle with Angular UI grid for date editing. Don't know if you can set a custom template to be sure you are using Angular Moment Picker, but I'm enough sure that this field is not using Moment Picker directive.
