### ISSUE TITLE
moment-picker in form stays pristine

### ISSUE THREAD

**Issue by AKFourSeven** [indrimuska/angular-moment-picker#18]
Hi

I am working with moment-picker in forms and when I make a change to one of my input that has a moment-picker associated to it I noticed that though the date has changed  and is displayed in the input, the model does not seem updated in all the case and the form  (or the element with the moment-picker) stays pristine, maybe I am missing something.
Here is the code displayed:
![capture d ecran 2016-03-16 a 11 26 36](https://cloud.githubusercontent.com/assets/1001256/13809257/212c9670-eb6a-11e5-96c9-e6a4b3c74f4b.png)

I took a picture of the code instead of the actual code to give you an idea of it as it is somewhat complex!

I really don't get what is going on, surely I am missing something.
And I don't know what is the use of the style attribute in the tags...

**Comment by indrimuska** [comment]
Hi @AKFourSeven, this seems to be related to #17.
Have you already tried the latest version of Angular Moment Picker?

**Comment by AKFourSeven** [comment]
Nope I haven't, I will try updating and keep in touch with you.

**Comment by AKFourSeven** [comment]
Hi after updating I can confirm that the issue is different, the problem still remains. It seems as though the calendar has been updated as well as the input , something prevent to trigger the watches on the form to set the element (and thus the form) to dirty.
I have been using this plugin for a while and never experienced that before (it might be because I never confronted the case).

**Comment by indrimuska** [comment]
Ok, let's take this [plunker](http://plnkr.co/edit/BtwqfZeidMyKNPC4zvdk?p=preview).

Angular does not unset `$pristine` property when a model has been changed through javascript, it sets the value to `false` only when a user interacts with a given input.
That being said, I think that the best solution for you is to set the pristine state by yourself when model changes, using the native angular api `$setDirty()`:

```javascript
$scope.$watch('myDate', function (myDate) {
   if (angular.isDefined(myDate)) {
      form.myDate.$setDirty();
   }
});
```
Check out this plunker: http://plnkr.co/edit/QhBoLzbHm48LGWrhhYb0?p=preview

**Comment by AKFourSeven** [comment]
I see the angle you are tackling this from. But I cannot get the form object  from within the link function.
I'll try to find a way to do that and post it here once I have found it, thanks for the tips though!

**Comment by indrimuska** [comment]
If you have a directive with a link function maybe you need to check your scopes.
This is a very simple [plunker](http://plnkr.co/edit/F2OVSAjpB5uBGvzhETaP?p=preview) that makes use of a directive with no private scope.

**Comment by indrimuska** [comment]
I'm going to close this issue since it seems there's not due to Angular Moment Picker.
Feel free to reopen it if you find any problem.

**Comment by AgDude** [comment]
I haven't actually replicated this, but I am sure it is due to the fact that moment-picker does not use ngModel. ngModelCtrl methods handle setting pristine/dirty state.
