### ISSUE TITLE
How to set today date an current time as default in angular-moment-picker  ?

### ISSUE THREAD

**Issue by EssenKh** [indrimuska/angular-moment-picker#187]
I want to set angular today's date and current time in angular-moment-picker. what is the attribute to use ? in tag on in config 
Regards

**Comment by indrimuska** [comment]
Hi @EssenKh, set today's date to your `ng-model` date property or `moment-picker`. See README for the differences.

**Comment by gopal-g** [comment]
You mean like this ? 

`$scope.myDate = new Date();`

or should i set a moment date objekt?
