### ISSUE TITLE
Display Minute view in 24 hour clock format

### ISSUE THREAD

**Issue by luludpsalmist** [indrimuska/angular-moment-picker#188]
Everything works fine with the date picker except that When I come to select  minutes , the clock format changes to a 12Hr clock . I would like to have a 24Hr clock format same as in the 'Hour View'
for instance if I select 23:00 in the hour view , the minute view displays 12hr clock so to select minutes I have to choose 11:01 , 11:02 e.t.c 
How do i get to be 24 hr clock for minutes view ?

**Comment by kalle17** [comment]
I had the same problem and solved it by setting "locale" property of picker to some momentjs language setting that use 24 h format by default e.g. 'en-gb'

**Comment by luludpsalmist** [comment]
That's just brilliant! It worked.

**Comment by jlubeck** [comment]
I have the opposite problem. I want both hs and minutes to be in the 12hr format. But using locale as en-us doesn't seem to fix the problem. It's still showing hs in 24hs and minutes in 12hs. Anybody had success in fixing this?

**Comment by csimpi** [comment]
@kalle17 didn't work for me and there isn't any better workaround you can set the minute format with the provider though but that doesn't allow us to change the format on the fly
