### ISSUE TITLE
CDN error

### ISSUE THREAD

**Issue by julianibarraprofite** [indrimuska/angular-moment-picker#19]
500 Internal Server Error

http://rawgit.com/indrimuska/angular-moment-picker/master/dist/angular-moment-picker.min.js
http://rawgit.com/indrimuska/angular-moment-picker/master/dist/angular-moment-picker.min.css

**Comment by indrimuska** [comment]
Hi @julianibarraprofite,
CDN is maintained by GitHub, there's nothing I can do to help you with.
Alternatively, you could try these links:

http://cdn.rawgit.com/indrimuska/angular-moment-picker/master/dist/angular-moment-picker.min.js
http://cdn.rawgit.com/indrimuska/angular-moment-picker/master/dist/angular-moment-picker.min.css
