### ISSUE TITLE
Set ng-model in UTC

### ISSUE THREAD

**Issue by pilouk** [indrimuska/angular-moment-picker#194]
Is there a way that the ng model is the UTC of the current selected date ?

ng-model-options="{timezone: 'utc'}" doesn't seem to be supported

**Comment by kkiernan** [comment]
I am actually having the opposite problem. It seems to display in the local timezone, but the model value is UTC. You don't see the same?

**Comment by pilouk** [comment]
Ur right i realize it when i pushed it to my server. So it's solved my
problem
