### ISSUE TITLE
How to set a 24 hours format value

### ISSUE THREAD

**Issue by gcaferra** [indrimuska/angular-moment-picker#2]

**Comment by gcaferra** [comment]
this happen when you are not using AM/PM

**Comment by indrimuska** [comment]
Hi @gcaferra,
I'm not sure to understand your issue, could you please provide a [Plunker](http://plnkr.co/edit/LzlOVb?p=preview) showing your problem or a valid option-set using the [Angular Moment Picker Builder](http://indrimuska.github.io/angular-moment-picker/#builder)?

**Comment by gcaferra** [comment]
has you can see when I select 18 he switch to 6 in the seleciton but not in the header then  you can only select 6:xx but the intention was 18:xx

![datepicker bug](https://cloud.githubusercontent.com/assets/8588065/11442742/2d7e0704-9518-11e5-9bce-9ccd0a1f8b52.gif)

**Comment by indrimuska** [comment]
Ok @gcaferra, now I understand what is your problem. 

Probably, you're setting a `format` option to any a 12 hours time token `"h"` or `"hh"`.

As you can see from the [moment.js guide](http://momentjs.com/docs/#/displaying/) `"HH"` format token is used to display 24 hour time, different from `"hh"` (used in combination with `"a"` or `"A"`) to display 12 hour time formats with meridiem label.

Try to change your `format` property to force a 24 hours time as in the following plunker (ps: I think that your locale language is German, isn't it?):
http://plnkr.co/edit/IRw25e8bhutalNwOD81c?p=preview

Let me know if this solves your issue.

**Comment by gcaferra** [comment]
Sorry for  the late answer,
 thank you for your help it worked but still a little graphic problem. Watch here:

![calendarbug](https://cloud.githubusercontent.com/assets/8588065/11592371/5ca7b4ae-9a9e-11e5-8354-b96ebddfdff5.gif)

the final result is correct but the user get confused from the 24HH-12HH in the Sub Hour selection

**Comment by indrimuska** [comment]
Yes, this is because the minute labels in `hour` view are defined by the property `minutesFormat` in the [provider](https://github.com/indrimuska/angular-moment-picker#momentpickerprovider) and its default value is your moment locale format without the meridiem part (am/pm):
```javascript 
moment.localeData().longDateFormat('LT').replace(/[aA]/, '')
```

So you could opt one of these options:

1. change your moment locale language globally: `moment.locale('fr')`
2. change the `minutesFormat` property of the provider:

```javascript
angular
    .module('myApp', ['moment-picker'])
    .config(['momentPickerProvider', function (momentPickerProvider) {
        momentPickerProvider.options({
            minutesFormat: 'HH:mm'
        });
    }]);
```
