### ISSUE TITLE
Moment Picker wont work on UI Modal

### ISSUE THREAD

**Issue by ccarlos009** [indrimuska/angular-moment-picker#205]
i try to use the angular-moment-picker directive inside modal and this directives dont work

**Comment by dtkern** [comment]
The problem can be the CSS property z-index. Try changing it to a higher value.

I was facing the same problem and solved adding it to my custom CSS:

1. (didn't work, couldn't understand why)
.modal div.moment-picker,
.modal-dialog div.moment-picker,
.modal-content div.moment-picker
{
  z-index: 5000 !important;
}

2. worked fine but it overrides the z-index for all moment-pickers, inside a modal or not.
.moment-picker
{
  z-index: 5000 !important;
}

Good luck!

**Comment by ccarlos009** [comment]
@dtkern works fine .. Thanks :D
