### ISSUE TITLE
Support of Angular 1.5+

### ISSUE THREAD

**Issue by christianklock-iglu** [indrimuska/angular-moment-picker#22]
Currently, you have a dependence on Angular "~1.4.3". From my point of view (and with my manual testing), the current version works perfectly fine with Angular versions above 1.5 as well.

For that reason, I propose to update your bower.json to a later version of Angular.

**Comment by indrimuska** [comment]
Hi @christianklock-iglu.
Well, Angular Moment Picker works with Angular starting from v1.3, but I don't know which syntax is used to specify that in bower? `>=1.3`? `^1.3`? Also, I don't if this syntax means for bower to look for the most recent version of the dependency.
What do you think you about?

**Comment by christianklock-iglu** [comment]
Hi @indrimuska,

In that case, "^1.3" should be the expression you were looking for. 

(There are quite some references on this online, eg. http://fredkschott.com/post/2014/02/npm-no-longer-defaults-to-tildes/).

All the best,
Christian

**Comment by indrimuska** [comment]
Thank you man, I will update it soon! 👍
