### ISSUE TITLE
disable specific dates using an array of dates.

### ISSUE THREAD

**Issue by 16code** [indrimuska/angular-moment-picker#223]
Hi,
I want disable specific dates using an array of dates.

**Comment by SpNk69** [comment]
Same here.

**Comment by 1f47a** [comment]
Please make sure you search the closed issues for your question before opening your issue.

You can check #189 for how to disable specific dates

**Comment by 1f47a** [comment]
My apologies, I see that the helpful part of the issue I linked was added after you had opened this issue.
