### ISSUE TITLE
funny jump in Mozilla firefox

### ISSUE THREAD

**Issue by circy** [indrimuska/angular-moment-picker#23]
In Mozilla Firefox, if you click in the Date Picker dialog jumps to a different spot. This happens only in Mozilla Firefox. Most significant of these is clear effect noticeable when the datpiker depends to a input field. This is adjustable with the demo website.

http://indrimuska.github.io/angular-moment-picker/

my code:
```
<div class="form-group">
         <label>XXX</label>
         <input type="text"
                  class="form-control input-sm"
                  moment-picker="XXXX.creatObject.buyDate"
                  min-view="month"
                  max-view="month"
                  placeholder="XXX"
                  value="{{XXX.creatObject.buyDate | amDateFormat: 'DD.MM.YYYY'}}"
                  required>
</div>
```

**Comment by cauealves** [comment]
Hello @circy, this is the problem?

![captura de tela 2016-04-21 as 15 31 22](https://cloud.githubusercontent.com/assets/7065285/14720114/2e7ef7b8-07d6-11e6-8a34-6de2e9a7996f.png)

**Comment by indrimuska** [comment]
Ok, now I am able to see the problem on FF.
I'm working for a fix..

**Comment by cauealves** [comment]
👍

**Comment by circy** [comment]
@cauealves Yes. ;)
@indrimuska Thanks, you made my Day! :) :+1:

**Comment by indrimuska** [comment]
Well, the solution is really simple, but it may affect existing pickers:
```css
.moment-picker { display: inline-block; }
```
Anyway, I think it's the best solution, so I'm going to pack a fix soon.

**Comment by indrimuska** [comment]
[v0.4.2](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.4.2) is now out with this fix!
Let me know if the problem still persists. :)

**Comment by circy** [comment]
First of all thank you, but I still have a problem that now fix is related to yours.
When using Twitter Bootstrap and a label and including making a text box will, you can not.
So the label is no longer on the text box but beside.
This is due to your fix in css.

`.moment-picker { display: inline-block; }`

my code:

```
<div class="form-group">
                    <label>XXXXX</label>
                    <input type="text"
                           class="form-control input-sm"
                           moment-picker="XXXXX.creatObject.nextService"
                           min-view="month"
                           max-view="month"
                           placeholder="XXXX"
                           value="{{XXXXXX.nextService | amDateFormat: 'DD.MM.YYYY'}}"
                           required>
                </div>
```

But thanks again I fix it in my code.

**Comment by indrimuska** [comment]
Oh sorry, I'm going to look for another workaround.

**Comment by circy** [comment]
You saved my day. Thank you!

**Comment by indrimuska** [comment]
Well, I think I got a solution!
Check out this plunker: http://plnkr.co/edit/YHqEhrdCCysDS2eZk9GM?p=preview

**Comment by circy** [comment]
okay, very very nice work!

**Comment by indrimuska** [comment]
Perfect, give me five to release a new version.

**Comment by indrimuska** [comment]
Thank you guys for reporting this! :)

**Comment by circy** [comment]
I have to thank! :)
