### ISSUE TITLE
Add ability to select from range of years

### ISSUE THREAD

**Issue by bruninho** [indrimuska/angular-moment-picker#24]
Hi, 

Currently the datepicker view filtering only goes up to "Year view" where you can select the months. Adding the ability to go an additional step back and select from an range of years is essential when selecting for example a date of birth. 
![datepickeryearview](https://cloud.githubusercontent.com/assets/8948393/14847932/2540fcdc-0c63-11e6-91fe-145674b5f21e.JPG)

Thanks, Bruno.

**Comment by indrimuska** [comment]
Hi @bruninho, this will be a very useful feature. Are you interested in making a PR?

**Comment by indrimuska** [comment]
This is now available in v0.5. Check it out! :)
