### ISSUE TITLE
Does the start-date attribute work?

### ISSUE THREAD

**Issue by altbdoor** [indrimuska/angular-moment-picker#246]
In reference to the documentation, it states that the `start-date` attribute is:

> Two-way bindable property representing the initial date to be shown in picker (as String in the same format of the value, or as a Moment.js object).

So I assume it will set a default value when the page loads, however, on the [Plunker](https://embed.plnkr.co/rjFk9d) link provided, there is no default date at all.

Is my understanding of the attribute `start-date` wrong, or is it not working?

**Comment by reidark** [comment]
The `start-date` don't set a default start value to your model, but a default start value to your moment picker.

To set a default value to your model use in your controller with `$scope.myVar` or with `ng-init`.

**Comment by altbdoor** [comment]
I see, so it was my misunderstanding. Thanks for the clarification!
