### ISSUE TITLE
Style current day

### ISSUE THREAD

**Issue by MrBuggy** [indrimuska/angular-moment-picker#26]
Hi indrimuska

First at all I would thank you for this great date-picker, it's awesome!

I have a problem with the styling of the picker: Everything works fine with the style, I have only the question, is there a class or somethin else, which can style the current day. For example: Today is the 02.05.16, but i select the 05.05.2016. So I would style the selected and the current day in the same time. So I can see the todays date and the selected. At the moment I only style the selecet. Is there a specific class for styling the current day. I often saw such classes for todays date in other date-picker plugins.

It would be great if you can help me.

Greetings
MrBuggy :-)

**Comment by indrimuska** [comment]
Hi @MrBuggy, thank you for the kind words!
I was thinking about adding a new feature to let users have a ready-to-use property to enable/disable highlighting of the current date. What do you think about? Are you interested to create a PR?

**Comment by indrimuska** [comment]
FYI latest release [v0.5.2](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.5.2) has a new boolean `today` property to highlight the current date.

**Comment by MrBuggy** [comment]
Very cool thanks! :D

Von meinem iPhone gesendet
