### ISSUE TITLE
Problem with browserify?

### ISSUE THREAD

**Issue by Gargamil** [indrimuska/angular-moment-picker#28]
Hi,

after installing your module with bower (and moment.js) i've tried to require it with browserify. 
Everything seems to work perfect, but when i try to require it in my angular app (v.1.5.5) `angular.module('backEndApp', ['moment-picker']);` an `Failed to instantiate module backEndApp due to:
Error: [$injector:modulerr] ` error pops up.. 

Sorry. Problem at my configuration. Solved it. Everything okay with this module and browserify

**Comment by indrimuska** [comment]
Hi @Gargamil, have you already solved your issue?

**Comment by Gargamil** [comment]
Yes, it was a damn caching Problem... 
Couple of hours to solve..
