### ISSUE TITLE
The will popup will go under other elements

### ISSUE THREAD

**Issue by crissi** [indrimuska/angular-moment-picker#3]
![image](https://cloud.githubusercontent.com/assets/3076578/11563807/32fdb6da-99d6-11e5-8e0c-5723f67290a5.png)

Maybe an option to set the position from the document/window instead?

**Comment by indrimuska** [comment]
Hi @crissi,
Angular Moment Picker now uses a *css workaround* to append the picker just below the selected element/input, and I know this may causes errors like the one you report.
By now, you could resolve this by creating a custom stylesheet that overrides the default stylesheet.

This is because Angular's jqLite ([docs](https://docs.angularjs.org/api/ng/function/angular.element)) does not provide an `.offset()` and a `.position()` methods like jQuery.

Anyway if you'd like to file a PR to resolve this I would review it. :)

**Comment by checklist** [comment]
Hi,
What should be in the custom stylesheet to override this?

Thanks!

**Comment by indrimuska** [comment]
Hi @checklist, it depends on your application, the first thing you could do is to check the zIndex of your elements and give to the `.moment-picker-container` the highest one ([currently](https://github.com/indrimuska/angular-moment-picker/blob/master/src/angular-moment-picker.css#L4) its value is 5).

**Comment by checklist** [comment]
Thanks. I tried that but with no success already before. I ended by remving the "before" .

Great lib. Thanks!

**Comment by AKFourSeven** [comment]
Hi @checklist I tried removing the :before as you suggested to no avail, it might be that I was targeting the wrong one.
Do you remember which one was it ?
Or better yet @indrimuska has the problem been solve in a newer version ?

**Comment by checklist** [comment]
Sorry but we could not solve the issue. This issue is repeating in many places and z-index changes we make do not affect the popup. Kinda gave up :-1:

**Comment by indrimuska** [comment]
The best solution is to allow users to append the picker to the body, but it implies to retrieve the absolute position (x, y) of the text input. This is easy to do perform with jquery, but unfortunately jqLite doesn't have that support. So the only way to achieve this goal is to create a jquery-like `position()` function.

**Comment by AgDude** [comment]
The current solution of including the view inline can cause issues with some layouts as well as the problems described here. I suggest taking the `$uibPosition` factory from https://github.com/angular-ui/bootstrap/blob/master/src/position/position.js (with proper attribution).  The [`$uibPosition.positionElements`](https://angular-ui.github.io/bootstrap/#/position) method does everything we need here for positioning.

In my fork I have started using that factory by adding a dependency on ui-bootstrap (since I was using it for other features anyway). Ideally angular-moment picker would have two builds, one that included $uibPosition and another that relied on ui-bootstrap, so as not to include it twice.

**Comment by indrimuska** [comment]
Thank you @AgDude for you suggestion. Some commits ago, I added the [`getOffset()`](https://github.com/indrimuska/angular-moment-picker/blob/master/src/angular-moment-picker.js#L46-L59) method ("borrowed" from [jQuery's offset api](https://github.com/jquery/jquery/blob/305f193aa57014dc7d8fa0739a3fefd47166cd44/src/offset.js#L78-L119)). I haven't try it out yet, but I will do when I'll have some spare time. However, I really don't want to depend to any other lib or plugin, just the AngularJS framework (if I had added jQuery's dependency, this issue would have been already closed).

**Comment by Adoniasv** [comment]
+1 - I have the same problem w Angular Material Dialog

![captura de pantalla 2016-11-01 a las 2 06 18 p m](https://cloud.githubusercontent.com/assets/5178330/19898905/b8db8562-a03c-11e6-8e55-4d2b1d174cca.png)

**Comment by ericdecarli** [comment]
YMMV - had the same problem and added these overrides to fix it

`position: initial;` for `moment-picker` class
`top: initial;` for `moment-picker-container` class

**Comment by simonemazzoni** [comment]
Same problem using angular material. @ericdecarli suggested fix doesn't work.
I don't understand why the z-index attribute doesn't work.

**Comment by CasperJ** [comment]
@simonemazzoni and @Adoniasv: I have the same problem in Angular Material as you.
I've made some progress. After inspecting how the "native" md-select is getting around this, I could see that the `moment-picker` needs to be moved out of the `md-dialog`. So I wrote a small directive to do that. I'ts kind of hacky, but it gets the job done:

```js
(function () {
    'use strict';

    angular
        .module('core')
        .directive("inDialog", FixMomentPickerWhenInDialog);

    /** @ngInject */
    function FixMomentPickerWhenInDialog() {
        return {
            restrict: 'A',
            link: function (scope, ele, attrs, ctrl) {
                var mdDialog = $(ele).parents(".md-dialog-container");
                if (mdDialog.length == 0) return; /* Not inside a dialog*/

                var pickerContainer = $(ele).parent().parent().find(".moment-picker-container");

                var newPickerTopContainer = $('<div class="moment-picker"></div>');
                $(mdDialog).append(newPickerTopContainer);
                newPickerTopContainer.append(pickerContainer);

                angular.element(ele).contents().scope().picker = newPickerTopContainer;
                newPickerTopContainer[0].style.top = "100px";
                newPickerTopContainer[0].style.left = "-500px";
            }
        }
    };
})();
```
Put it on your moment-picker like this `<span moment-picker ... in-dialog></span>` and you will end up with this:

![image](https://cloud.githubusercontent.com/assets/2158013/22804213/469f0d40-ef18-11e6-9265-6033775b2069.png)

As you can see I'm almost there, but CSS positioning is beyond my understanding, so I can't quite figure out how to get the measures right (and get rid of the hard-coded pixels).

Maybe someone with CSS-ninja skills can finish this?

Cheers!

**Comment by Halsys** [comment]
I fixed my issue by overriding my content body overflow to visible. Which turns off clipping and doesn't add a scroll bar to the div. Angular Material had set `overflow: auto;` for md-content which caused the clipping described here. Might help somebody else using angular material. I'm fine with being unable to scroll in md-content when the whole page can still be scrolled normally. Good luck!

**Comment by indrimuska** [comment]
Finally, this should be fixed in the [latest version](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.10.0) (v0.10.0)!
