### ISSUE TITLE
Using Jalali Date in picker

### ISSUE THREAD

**Issue by mehr30na** [indrimuska/angular-moment-picker#30]
Thanks for your good and useful work, I have one issue which is using Jalali date in your picker. And also there is [Jalali Moment ](https://github.com/jalaali/moment-jalaali) which is Jalali version of moment.js. 

Please kindly help me come up with this issue.

**Comment by indrimuska** [comment]
I'm sorry @mehr30na, at the moment Angular Moment Picker does not support any other framework different from Moment.js. To support Jalali Moment it requires to be extended to support its tokens (ie `jYYYY`, `jM`, `jD`, ...) and its methods (ie `jYear`, `jMonth `, `jDate`, ...).

If you are interested in implementing this feature, I will be happy to review your PR.

**Comment by azerafati** [comment]
I would be happy to pickup on this and extend Angular Moment Picker to support Jalali, please put me on the right track on the implementation process.

**Comment by azerafati** [comment]
Should we add an `Attribute` which let's choose the moment framework as the default and could be changed to Jalali or something else?
