### ISSUE TITLE
Decade view is not working

### ISSUE THREAD

**Issue by shubhamkes35** [indrimuska/angular-moment-picker#31]
Very smooth and smart picker. One issue that i noticed is decade view is not working for me. And its not even working on builder example. 
http://indrimuska.github.io/angular-moment-picker/

I cant see year selector in the picker.

**Comment by dschnelzer** [comment]
If you are using bower, you need to use 

"dependencies": {
    "angular-moment-picker": "indrimuska/angular-moment-picker"

Are you doing that?  If you just use 

"dependencies": {
    "angular-messages": "1.5.3",
    "angular-moment-picker": "angular-moment-picker"

you are pointing to an older version at https://github.com/alanjhonnes/angular-moment-picker

**Comment by indrimuska** [comment]
@shubhankes35 the default view when you open the picker is the *Year view*. You can change it by setting the attribute `start-view` to `decade`.

**Comment by shubhamkes35** [comment]
I did try that , but it does not seem to work . Changed min-view and start-view to "decade". But It did not help . Even on your working example it does not work . Please help me .

**Comment by indrimuska** [comment]
I've just created this [plunker](http://plnkr.co/edit/rbLXTFvJCOBwItXT4U7u?p=preview) and everything seems work as expected.
Could you please provide a working example showing this issue?

**Comment by shubhamkes35** [comment]
I fetched using bower, which gave me v 0.4.2 
Problem is solved in 0.5 . Thank you

**Comment by indrimuska** [comment]
Glad to hear you've solved! :)
