### ISSUE TITLE
Moment object and calendar start day

### ISSUE THREAD

**Issue by taufnrsyd** [indrimuska/angular-moment-picker#33]
Is there anyway that I could grab the date as a Moment object instead of the formatted string? Also, it might be useful to have an option to set the first day of the calendar since it's different here (we start our weeks on Monday).

**Comment by indrimuska** [comment]
Hi @taufnrsyd, Angular Moment Picker just returns strings, not object. There's no way at the moment to get the moment object from the directive, but you can have your own Angular Filter to achieve that.

Regarding the first day of the week, it depends on the `locale` you've set for the picker (i.e `en-gb` starts the week from Monday; instead `en-us` starts from Sunday). Check out the demo page at http://indrimuska.github.io/angular-moment-picker/#locales.
