### ISSUE TITLE
bower install not found

### ISSUE THREAD

**Issue by adampbragg** [indrimuska/angular-moment-picker#34]
$ bower install moment-picker
bower                        ENOTFOUND Package moment-picker not found

I would love to be able to install this via bower. What am I missing?

**Comment by indrimuska** [comment]
Well, I've just  tried that command and its works perfectly on my pc.
I can't help you, maybe you're a using some kind of repository list cache?
The simplest thing you can do is to reinstall bower. Hope this helps!

**Comment by adampbragg** [comment]
Yea, I just found out we have a private bower registry proxy. Added it and I am good. Thanks for entertaining my question.

**Comment by indrimuska** [comment]
Glad to hear you've solved! :)
