### ISSUE TITLE
Add possibility to navigate with keyboard and validate with "enter"

### ISSUE THREAD

**Issue by Simobain** [indrimuska/angular-moment-picker#36]

**Comment by indrimuska** [comment]
Hi @Simobain, very interesting feature! I really don't know when it will be implemented, because I don't have too much spare time at the moment, but if you are interested in creating a pull request I'll be glad to review it for you. :)

**Comment by indrimuska** [comment]
FYI, this feature is now available in the latest release [0.6.0](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.6.0).
