### ISSUE TITLE
minDate, maxDate binding

### ISSUE THREAD

**Issue by GeorgeKnap** [indrimuska/angular-moment-picker#38]
Trying to set the min date and max date dynamically by angular expression but doesn't work. Only hardcoded values works.

this is the code:
```
data-min-date="'{{::ctrl.data.minDate}}'"
data-max-date="'{{::ctrl.data.maxDate}}'"
```
and in the controller's constructor:
```
this.data = {
            minDate: moment().subtract(24, 'hours').format('LLL'),
            maxDate: moment().format('LLL')
        };
```
inspecting the rendered component looks like this:
```
<div class="input-group ng-isolate-scope moment-picker-contents" data-moment-picker="ctrl.data.dataFrom" data-locale="en" data-format="LLL" data-min-view="day" data-min-date="'June 12, 2016 11:00 AM'" data-max-date="'June 13, 2016 11:00 AM'" data-today="true">
                            <span class="input-group-addon">
                                <i class="fa fa-clock-o" aria-hidden="true"></i>
                            </span>
 <input class="form-control input-sm ng-pristine ng-untouched ng-valid ng-not-empty" placeholder="Select a time" data-ng-model="ctrl.data.dataFrom" data-ng-model-options="{ updateOn: 'blur' }">
 </div>
```

which looks fine but the picker allows me to select any date freely.

Hardcoding this values to html makes it work but that's just not an option.

Thank you.
George

**Comment by indrimuska** [comment]
Give me 5 to create a plunker to see if everything works fine, then I'll get back to you..

**Comment by indrimuska** [comment]
Ok, I analyzed your scenario and I see that you use one-time binding, but `max-date` and `min-date` are dynamic properties that can be update with two way data binding. So the simplest solution you can have is to update `min-date="'{{::ctrl.data.minDate}}'"` to `min-date="ctrl.data.minDate"`.

Check out this plunker: http://plnkr.co/edit/rbLXTFvJCOBwItXT4U7u?p=preview

**Comment by GeorgeKnap** [comment]
@indrimuska  Works great! Thank you for a quick solution.

**Comment by indrimuska** [comment]
You're welcome! :)
