### ISSUE TITLE
 Value not refreshed in the controller

### ISSUE THREAD

**Issue by marco10024** [indrimuska/angular-moment-picker#39]
Bonjour : 

`<div moment-picker="meeting" format="HH:mm A" change="$ctrl.onChange(newValue, oldValue)">The meeting starts at {{ meeting }}.</div>         `       

```
self.onChange = function() {
       console.log($scope.meting);
};
```

console.log return the old value . Is this normal ?

**Comment by indrimuska** [comment]
Mmmh @marco10024, you're right! That's not a correct behavior, that's why I'm going to change it. However, at the moment you can use the two parameters passed through your `$ctrl.onChange` method:
```javascript
self.onChange = function (newValue, oldValue) {
   console.log(
      'newValue = ', newValue,
      'oldValue = ', oldValue
   );
};
```

**Comment by indrimuska** [comment]
Last release, v0.5.5, contains the update above.
Now when `change` is fired model value contains the new date.
Thank you @marco10024!
