### ISSUE TITLE
Format causing issues with returned data

### ISSUE THREAD

**Issue by ljfolino** [indrimuska/angular-moment-picker#4]
I am using angular-xeditable with angular-moment-picker. I have the moment picker working on the xeditable text fields.  The issue I am having is when I select a time the minutes are being lost.  This onlt seems to happen when using a format with the picker.  What is odd is the fact that this does not happen all the time or on all the controls I have the picker bound to.  Currently I have the picker bound to multiple controls.

**Comment by indrimuska** [comment]
Hello @ljfolino,
I have never used angular-xeditable before, could you please provide a Plunker to see the behavior you're describing?

**Comment by ljfolino** [comment]
So this behavior seemed to stop.  I think it was  a scope issue or non closed element.  Thanks for the quick response.

**Comment by indrimuska** [comment]
You're welcome!
