### ISSUE TITLE
Hour format is lost when displaying the minutes popup

### ISSUE THREAD

**Issue by vivelys** [indrimuska/angular-moment-picker#40]
First of all : Great Work ! It saved my time (many time)

I've localized the moment picker to French.
When I select the day in the picker, the hour popup is displaying with hours from 00:00 to 23:00 (it is normal)
but when I choose **15:00**, the next popup displays minutes from **3:00** to **3:59**.
It should be from **15:00** to **15:59**

Did I miss something ?

Regards

**Comment by indrimuska** [comment]
Hi @vivelys, thank you very much for these kind words! :)
To solve your problem you can just set the `minutes-format ` property in the [momentPickerProvider](https://github.com/indrimuska/angular-moment-picker#momentpickerprovider): actually, it's set to the the locale format LT without meridiem part.

Well, it should be set to that value, but it's not. As I can see, French format for **4pm** should return `16:00`, but it gets just `4:00`. So, it needs a little change to the plugin (give me one or two days, I'll do it in my free time) but, anyway, you can use momentPickerProvider and set it as above:
```javascript
momentPickerProvider.options({
   minutesFormat: 'HH:mm'
});
```

**Comment by indrimuska** [comment]
Check out last release of the directive and enjoy! :)

**Comment by vivelys** [comment]
Hello,

I Wonder if the line 408 (in the .js file) shouldn't be : 
minutesFormat = moment.localeData($scope.locale).longDateFormat('LT').replace(/[aA]/, '') || momentPicker.minutesFormat;

**Comment by indrimuska** [comment]
Well, if you change the line as you said, you will never get the provider's value, because the part on the left side of the OR-statement will always be "true".

**Comment by vivelys** [comment]
ok, but when I hit the breakpoint I put on this line, momentPicker.minutesFormat has a value of 'h:mm' and this side of the OR statement is also TRUE

**Comment by vivelys** [comment]
In fact I have :

```
app.config(['momentPickerProvider', function (momentPickerProvider) {
        momentPickerProvider.options({
            /* Picker properties */
            locale:        'en',
            format:        'L LTS',
            minView:       'decade',
            maxView:       'minute',
            startView:     'year',
            today:         false,            
            /* Extra: Views properties */
            leftArrow:     '&larr;',
            rightArrow:    '&rarr;',
            yearsFormat:   'YYYY',
            monthsFormat:  'MMM',
            daysFormat:    'D',
            hoursFormat:   'HH:[00]',
            minutesFormat: moment.localeData().longDateFormat('LT').replace(/[aA]/, ''),
            secondsFormat: 'ss',
            minutesStep:   1,
            secondsStep:   1
        });
    }]);

```
and in my html code :
 ```
<div class="input-group" moment-picker="obj.AnalysisDate" start-view="month" minutesStep = 1 maxView="minute" locale="{{moment.locale()}}" >
  <input class="form-control" id="analysisDate" name="analysisDate" ng-model="obj.AnalysisDate" ng-model-options="{ updateOn: 'blur' }">
  <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
</div>

```
moment.locale() returns "fr" but it seems the value provided by the momentpickerprovider is used for this picker.

I think the definition of 'locale' in the div should overwrite the value set by the provider.

**Comment by indrimuska** [comment]
Well, the problem is in your code, just right here:
```javascript
momentPickerProvider.options({
// ...
    minutesFormat: moment.localeData().longDateFormat('LT').replace(/[aA]/, ''),
// ...
});
```

With this configuration, you want to override the default `minutesFormat` value with the one you've passed through. Since you've not specified the locale, you'll always be an English format value.

That being said, you have two way to solve this:

1. Do not specify any `minutesFormat` in the provider.
2. Update the default `minutesFormat` for all the picker using a French locale:
```javascript
minutesFormat: moment.localeData('fr').longDateFormat('LT').replace(/[aA]/, ''),
```
