### ISSUE TITLE
Using onChange : Model updated but not the calendar value 

### ISSUE THREAD

**Issue by ZeldaIsThePrincess** [indrimuska/angular-moment-picker#41]
Hi, thx for your awesome work, your moment picker is pretty useful.

However im facing a problem in this scenario : 

I have two dates, the second one is based on the first one (let's say : date b always = date a + 2 hours)

So when i change the first date, the change event is triggered and the second date must be updated. In this case, my model has the correct value but not the calendar value. The tricky part is that the change applies on the calendar once i set the focus on another field.

Might be related to #17 

Thx for your help.

**Comment by indrimuska** [comment]
Hi @ZeldaIsThePrincess, I think that you just need to `$apply` the new scope.
Take a look at [this plunker](http://plnkr.co/edit/BtwqfZeidMyKNPC4zvdk?p=preview), it can help you finding your issue. :)

**Comment by ZeldaIsThePrincess** [comment]
Thx @indrimuska, this worked like a charm !

**Comment by indrimuska** [comment]
Happy to hear you've solved your issue! 👍
