### ISSUE TITLE
Moment picker in fancybox

### ISSUE THREAD

**Issue by mike-diamond** [indrimuska/angular-moment-picker#42]
When I click on moment picker after load as inline fancybox, it outputs empty picker box. 
But if I click on a picker in input directly - all works fine.
Ho to fix?

**Comment by indrimuska** [comment]
Hi @mike-diamond, can you please provide a working example?

**Comment by indrimuska** [comment]
I'm going to close this issue, feel free to open again if you still find any problems. :)
