### ISSUE TITLE
How to get a Date Object?

### ISSUE THREAD

**Issue by sfakir** [indrimuska/angular-moment-picker#46]
The datepicker always transforms the model into a String according to format. The format should be only the way to visualize the model but NOT the stored format.

`<div moment-picker="currentUser.dateOfBirth" format="L" start-view="decade" max-view="day" class="form-control"></div>`

dateOfBirth = should by type Date oder moment(). How do I get the date object without parsing it again back with moment.js?

**Comment by sfakir** [comment]
Workaround like this:
`
$scope.updateDateOfBirth = function(newValue, oldValue){
          var m = moment(newValue, "L");
          $scope.currentUser.dateOfBirth = m.toDate();
          $scope.$apply();
        };
`

**Comment by indrimuska** [comment]
Hi @sfakir, since the model is always a String, that is the only solution to get a moment object according to the format you have chosen. You can also specify your locale as third parameter of the moment constructor like this:
```javascript
$scope.format = 'L';
$scope.locale = 'en';

$scope.onUpdate = function (stringDate) {
    $scope.birthDate = moment(stringDate, $scope.format, $scope.locale);
};
```
