### ISSUE TITLE
Dynamic `hoursFormat` value

### ISSUE THREAD

**Issue by 32teeths** [indrimuska/angular-moment-picker#49]
Awesome Library !! I am creating a range picker taking start time and end time . But I need to configure the end time such that if the start time is in 30 minutes past any hour (like 1:30 , 2:30) , the end time calendar should show only hours past 30 minutes in day view . The hoursFormat property is to be configured in the `config` section . Can it be done on the fly ?

**Comment by indrimuska** [comment]
Hi @32teeths, I don't think I've totally understand your problem.
You want to create a range picker. If the start time is -for example- 2:30 then you want to show in the day view of the end time hours in the format `"HH[:30]"`, isn't it?

Well, in the day view you only choose an hour, not a combination of hour+minute. Also, `hoursFormat` can be edited only globally using *momentPickerProvider*.

Anyway, you can find a workaround for your use-case, using a dynamic format value.
Check out this [plunker](https://plnkr.co/edit/yna6v4iniAi8nqUQegLs?p=preview), it may help with your app! :)

**Comment by 32teeths** [comment]
@indrimuska Thank you for the response and had a look at the plunkr. This would help . But I wanted the day view to show the minutes in the format of start time . Else , It would be like , the user selects a time , suppose 4:00 but will see 4:30 after selection which would make them feel that there is something wrong with the Datepicker .

**Comment by indrimuska** [comment]
Sorry, but as I said *dayView* is not born to let user select minutes, just hours in the selected day. Anyway, if you need help to fork the project and create your own version of the picker that allows to select a dynamic `hoursFormat` value, I'll be happy to help you!

**Comment by 32teeths** [comment]
@indrimuska I will surely give it a try .
