### ISSUE TITLE
Dynamic min-date

### ISSUE THREAD

**Issue by carlosrdv** [indrimuska/angular-moment-picker#52]
Hi. @indrimuska 
Is there a dynamic way to set the min-date value as today?
and is this possible for the hour?

Regards

**Comment by indrimuska** [comment]
Yes @carlosrdv, `min-date` is a two-way bindable property, so that you can change its value as you want. You only have to remember that it is a `String` in the same format of the value (i.e. "HH:mm").

```html
<div moment-picker="ctrl.meeting" format="HH:mm" min-date="ctrl.minDate">
    The meeting starts at {{ ctrl.meeting }}.
</div>
```
```javascript
ctrl.meeting = '16:20';
ctrl.minDate = '10:20';
```

Hope this helps! :)

**Comment by iosDev3** [comment]
It helped a lot! thank you! @indrimuska

**Comment by mahender-vutkuri** [comment]
is a there a way to set the start date dynamically?
in my case start date is different  from calendar to calendar so i need to set the start date dynamically.any help would be appreciated.
