### ISSUE TITLE
Day after DTS cannot be picked and double dates displayed

### ISSUE THREAD

**Issue by jenspettersson68** [indrimuska/angular-moment-picker#56]
If having brazilian timezone (UTC-3) set on computer (win7) and using Firefox it is not possible to pick the day after DTS in October. Also the picker is displaying two 15 October  (2016). 
It works OK in Chrome.
Tested in FF 45, Safari, IE11 timezone (UTC-03:00) Brasilia at http://indrimuska.github.io/angular-moment-picker/
Step by step to reproduce
1. Set timezone on computer to e.g. (UTC-03:00) Brasilia
2. Goto http://indrimuska.github.io/angular-moment-picker/ with FF, IE11 or Safari
3. Select October 2016 in the second input fields on the above link
Problem:
Two 15 October is present and 16 October is not possible to select

![image](https://cloud.githubusercontent.com/assets/22072695/18344625/65432fbe-758e-11e6-9e0f-d996a49e4cbd.png)

**Comment by jenspettersson68** [comment]
If choosing locale Swedish and October 2016 a whole week is missing

![image](https://cloud.githubusercontent.com/assets/22072695/18344594/50ea213a-758e-11e6-9703-374172f92047.png)

**Comment by indrimuska** [comment]
Wow, this is so weird! Thank you @jenspettersson68 for reporting this, I will investigate to know why this is happening.

**Comment by indrimuska** [comment]
Super weird. I don't see the error anymore in the demo page right now.
If it's confirmed, it could depends on the timezone or the current pc clock time.

![image](https://cloud.githubusercontent.com/assets/1561134/18450962/67e8b554-7935-11e6-8275-a0b82175958c.png)

**Comment by jenspettersson68** [comment]
It depends on the pc clock. If you choose Brazilian timezone on the pc you can reproduce it, like the first step above. I guess it's due to Brazil change  the DTS exactly 00.00 which triggers the behaviour. Most other timezones change time in the middle of the night around 02.00.

**Comment by indrimuska** [comment]
Yes, confirmed. As you said, it's due to the DST change. That's not a bug of the directive or Moment.js itself, but it seems to be caused by V8 engine ([ref.](https://github.com/moment/moment/issues/1231)).

Anyway I got a workaround: in month view I will parse days at midday, so that any DST change won't affect to any day adding. I'm going to patch next release.

**Comment by indrimuska** [comment]
This is now available in [v0.6.2](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.6.2). Thank you for your support! 👍
