### ISSUE TITLE
Cannot select DST day in Brazil with Firefox

### ISSUE THREAD

**Issue by jenspettersson68** [indrimuska/angular-moment-picker#58]
Set your computer timnezone to Brazil (UTC-3)
1. Go to demopage with Firefox
http://indrimuska.github.io/angular-moment-picker/#builder
2. Try to select 2016 October 16.
Problem:
The date copied to the input field are 15 october.
Reproducable in Firefox and IE11
(Works OK in Chrome)

**Comment by indrimuska** [comment]
Duplicate #57
