### ISSUE TITLE
Disable a day of the week 

### ISSUE THREAD

**Issue by carlosrdv** [indrimuska/angular-moment-picker#59]
is it posible to disable all sundays (for example) for future dates?

**Comment by indrimuska** [comment]
Hi @carlosrdv,
Well, actually Angular Moment Picker doesn't let you choose which days of the week will be disabled, but this would be a very interesting enhancement feature.
This will surely be one of the next features. :)

**Comment by indrimuska** [comment]
Thanks @carlosrdv for your tip! ;)

**Comment by azzra** [comment]
Hi this pr #62 could be working. Let me know if you want some changes as the code could be optimized.

**Comment by indrimuska** [comment]
Ok @azzra, I'm going to review your PR and get back to you! :)

**Comment by indrimuska** [comment]
This feature is now available starting from the release [v0.6.5](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.6.5).
Thanks to @azzra for sharing his idea!
