### ISSUE TITLE
Module name is incorrect in readme

### ISSUE THREAD

**Issue by drew-moore** [indrimuska/angular-moment-picker#6]
`var myApp = angular.module('myApp', ['moment-picker']);` results in a NOMOD error and failure to run.  

It only takes a quick glance at the source to notice that the module name is `momentPicker` and not `moment-picker` - and indeed `var myApp = angular.module('myApp', ['momentPicker'])` works fine - but to have the name of your module wrong at the top of your readme is an inexcusable oversight IMO.

**Comment by indrimuska** [comment]
Hello @drew-moore,
Thank you for writing and sorry for the late response.

You say that if writing `moment-picker` will cause an error during run, isn't it?
Maybe there is an angular naming convention system that I don't know yet, but as you can see in this [plunker](http://plnkr.co/edit/LzlOVb?p=preview) I don't have any errors if I add `"moment-picker"` as a dependency in my module.

Could you please provide an example showing this issue or, at least, a link where I can read and better understand naming conventions?
Thank you.

**Comment by martinmaillard** [comment]
I had the same issue and it was because I installed the wrong package from bower. "angular-moment-picker" is used by someone else : you have to install "indrimuska-angular-moment-picker".
I guess it would be nice to mention it in the docs.

**Comment by indrimuska** [comment]
Oouh! Sorry guys, I will update readme file as soon as possibile with all information to get Angular Moment Picker.

**Comment by indrimuska** [comment]
I just released version [0.1.4](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.1.4) with the instructions on how to get the module.
Let me know if this issue occurs yet.

Note that Angular Moment Picker is available on bower with these names:
* `moment-picker`
* `indrimuska-angular-moment-picker`

**Comment by martinmaillard** [comment]
Thank you ! I just upgraded and everything went fine

**Comment by indrimuska** [comment]
Happy to see you've solved!
