### ISSUE TITLE
Not open again after select a value

### ISSUE THREAD

**Issue by lfreneda** [indrimuska/angular-moment-picker#66]
After selecting a value, the picker container is not opening **until** clicking outside and then click on picker element again.

Check it out my gif:

![webm](https://cloud.githubusercontent.com/assets/372420/18933593/f5d722b0-85ab-11e6-9c0e-3f31279721c5.gif)

The same issue is happening on http://indrimuska.github.io/angular-moment-picker/ examples..

**Comment by Kluskey** [comment]
+1

**Comment by hweee** [comment]
+1

**Comment by nednil** [comment]
+ 1

**Comment by LuisEGR** [comment]
That doesn't happen to me

**Comment by lfreneda** [comment]
@LuisEGR r u using lasted version? :grimacing:

**Comment by LuisEGR** [comment]
well, now it happens, I tested in the examples page

**Comment by lfreneda** [comment]
@LuisEGR :dancers:

**Comment by indrimuska** [comment]
Hi guys, this is because the picker opens every time the input (or div) is focused. When you select a date from it, the focus still persist so you can open the picker again only after blur the container.
I'm looking for a solution, ideas are always welcome! :)

**Comment by lfreneda** [comment]
@indrimuska got it.. 

What if after selecting a date, set focus for the next form input (just like a tab), bad idea?

**Comment by LuisEGR** [comment]
If some one is not using more inputs that could be a problem, maybe doing something like this resolve the problem:

```javascript
var tmp = document.createElement("input"); document.body.appendChild(tmp); 
tmp.focus();
document.body.removeChild(tmp);
```

**Comment by lfreneda** [comment]
@LuisEGR your suggestion could be a workaround, but not a definitive a solution

**Comment by oracion-ns** [comment]
**angular-datepicker** had a similar issue:
[https://github.com/g00fy-/angular-datepicker/issues/281](url)
They fixed it by showing the picker on both `focus` and `click` events.

Maybe do the same?
[https://github.com/indrimuska/angular-moment-picker/blob/master/dist/angular-moment-picker.js#L693](url)
```
.on('focus click',   function () { $scope.$evalAsync($scope.view.open); })
```

**Comment by indrimuska** [comment]
Thank you @oracion-ns, I think the first option you posted is perfect for this issue!
I'm going to release a new version with this feature asap.

**Comment by indrimuska** [comment]
[v0.6.6](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.6.6) is already out! Thank you all! :)

**Comment by sergioRicardo1995** [comment]
This bug already fail -v 0.7.0
 
I fix this like @oracion-ns  said
(on $scope.view.change)

if ($scope.autoclose) {
    $timeout($scope.view.close);
    $scope.input[0].blur();
}
