### ISSUE TITLE
Hour view displayed incorrectly on locale='de'?

### ISSUE THREAD

**Issue by headyrules** [indrimuska/angular-moment-picker#67]
Hey there,

when i use locale='de', the hours go from 1-24 as it should be. Anyway, in the hour - view where i am supposed to pick something like 17:05 it says 5:05 instead on the buttons.Is this a bug or am i doing something wrong?

thanks for the help!

**Comment by indrimuska** [comment]
Hi @headyrules,

Moment Picker directive renders minutes in the Hours View using the setting in the [momentPickerProvider](https://github.com/indrimuska/angular-moment-picker#momentpickerprovider). As you can see from the README, the default value of `minutes-format` is set to "*Locale format LT without meridiem part (AM/PM, am/pm)*".

Indeed, German locale value of `LT` is equal to `h:mm A`, so removing the meridiem part will just return `h:mm`. Moment.js token [`h`](http://momentjs.com/docs/#/displaying/format/) gets the hour from 1 to 12 without adding the zero padding.

If you want to change this behavior, you just have to set the value you want using the picker provider, like this:

```javascript
angular
    .module('myApp', ['moment-picker'])
    .config(['momentPickerProvider', function (momentPickerProvider) {
        momentPickerProvider.options({
            minutesFormat: "HH:mm"
        });
    }]);
```
