### ISSUE TITLE
Add support for seconds

### ISSUE THREAD

**Issue by cdhowie** [indrimuska/angular-moment-picker#7]
It would be helpful if the picker could be used in contexts where it's necessary to select down to second precision.

**Comment by indrimuska** [comment]
Hi @cdhowie,
A new *Minute View* could be very useful for those who need seconds.
I also thought about creating a *Decade View* in order to show more years together.

Any PR will always be welcome! :)

**Comment by cdhowie** [comment]
I was indeed thinking of working on a PR. I'm new-ish to Angular so don't feel 100% comfortable working on it solo just yet but maybe in the near future.

**Comment by indrimuska** [comment]
Don't worry, I will look into this asap! :)

**Comment by indrimuska** [comment]
I just release [v0.2.0](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.2.0) with this feature!

**Comment by cdhowie** [comment]
Thanks very much!
