### ISSUE TITLE
Close the picker programatically?

### ISSUE THREAD

**Issue by george-i** [indrimuska/angular-moment-picker#72]
Is it possible? And how it can be done?

**Comment by indrimuska** [comment]
Hi @george-i, actually there is no APIs to do that, but you can trigger `blur` event to achieve that goal as a temporarily solution. I don't have too much time this period, but I will give an instrument to open/close the picker programmatically

**Comment by george-i** [comment]
Can you show an example of blur trigger?

In the end, this is what I want to achieve:
- click on calendar icon: open the date picker (working)
- click again on calendar icon: close the date picker (NOT working)

**Comment by indrimuska** [comment]
Well, if you use jQuery you can simple call `$element.trigger('blur')`.
I don't know if this is implemented even in jqlite.

**Comment by indrimuska** [comment]
Ok, you can simply use `.blur()` method.

```html
<span moment-picker="ctrl.today" format="YYYY-MM-DD">
	<i class="glyphicon glyphicon-calendar"></i>
	<input type="text" ng-mode="ctrl.today" placeholder="select a date..">
</span>
```

```javascript
var icon = angular.element(document.querySelectorAll('.glyphicon-calendar')[0]);
var input = angular.element(document.querySelectorAll('input')[0]);
var picker = angular.element(document.querySelectorAll('.moment-picker-container')[0]);

icon.on('click', function () {
	if (picker.hasClass('open')) input[0].blur();
});
```

**Comment by wickY26** [comment]
@indrimuska On my current project designers used flex for css and this is somehow trigger open function and datepicker never close and stuck in this loop.

ng-options blur solution is working, ability to open close datepicker programatically would be awesome and be more stable...

**Comment by wickY26** [comment]
I could do pr for this manual open/close features...

**Comment by indrimuska** [comment]
FYI, I've added a new `isOpen` property to let you open/close the picker programmatically.
https://github.com/indrimuska/angular-moment-picker/releases/tag/0.9.1
