### ISSUE TITLE
min date - show decade error

### ISSUE THREAD

**Issue by jaros93** [indrimuska/angular-moment-picker#74]
When i set min-date as 2008-11-07T00:00:00Z than i in decade view see only page 2009-2020. Button prev doesnt show.  In year view a can set 2008 year.

Sorry for my eanglish.

**Comment by indrimuska** [comment]
Hi @jaros93, I don't think I have totally understand your problem, but keep in mind that `min-date` value should have the same format of the model. So, if you set `format` to `"YYYY-MM-DD"`, you should set `min-date` to `"2008-11-07"`.

**Comment by jaroslawf** [comment]
@indrimuska not working :) 

My generated code:
![img2](https://cloud.githubusercontent.com/assets/14885210/20278879/a65be4f8-aaa6-11e6-96fd-a58db915d1d6.PNG)

In this a can't switch to page with min year.
![img1](https://cloud.githubusercontent.com/assets/14885210/20278878/a65bdcb0-aaa6-11e6-9b91-368d78bafab9.PNG)

I can select min year in this only.
![img3](https://cloud.githubusercontent.com/assets/14885210/20278880/a6614d80-aaa6-11e6-83d1-55a19432a9fd.PNG)

**Comment by jaros93** [comment]
@indrimuska not working :)

My generated code:
![img2](https://cloud.githubusercontent.com/assets/2663275/20279138/935f55c8-aaa7-11e6-81ed-f105e38fe441.PNG)

In this a can't switch to page with min year.
![img1](https://cloud.githubusercontent.com/assets/2663275/20279142/965d359c-aaa7-11e6-9254-5b3f1702257d.PNG)

I can select min year in this only.
![img3](https://cloud.githubusercontent.com/assets/2663275/20279143/969eef0a-aaa7-11e6-84f8-1db3e94cd47e.PNG)

**Comment by indrimuska** [comment]
HI @jaros93, you should use the same format for min/max date used for your model. This means, you have to change your code to `min-date="'1998-11'"`.

Check out at #52 .

**Comment by jaros93** [comment]
@indrimuska not working too.

![img1](https://cloud.githubusercontent.com/assets/2663275/20304652/b47f50f2-ab31-11e6-9f1c-2441a6c79cec.PNG)

But working for this.
![img2](https://cloud.githubusercontent.com/assets/2663275/20304656/b66c9d66-ab31-11e6-8dc5-01d9b9f762f3.PNG)

According to the test does not working for yers in last row for example: 
(...) 1997, 1998, 1999, 
2007,2008, 2009, 
2017, 2018, 2019, 
et cetera

I use this libraries
![img3](https://cloud.githubusercontent.com/assets/2663275/20304864/c1018466-ab32-11e6-8954-a4913162fd47.PNG)

**Comment by jaros93** [comment]
@indrimuska Did you check it?

**Comment by indrimuska** [comment]
@jaros93 I am unable to reproduce your issue, can you please share a working example to figure out where the problem is?

In the meantime, you could also check out this example: https://plnkr.co/edit/LjoPIpIHPr2ydHhiXcEx?p=preview

**Comment by mmai** [comment]
Here is an example. The min date is 1997 but we can't go back before 2000 in the decade view : https://plnkr.co/edit/v2UaOOq9xhs39HMuqg4D?p=preview

But if you set the min date to 1996 it works...
