### ISSUE TITLE
change event not fired when the input value is empty

### ISSUE THREAD

**Issue by sadashivm** [indrimuska/angular-moment-picker#75]
change event not fired when the input value is empty
<input type="text change="onchageEvent()" >
the above function is not working for if value is empty

**Comment by indrimuska** [comment]
Hi @sadashivm, I have created a plunker to verify this issue, but I haven't found anything wrong in it. You can take a look at https://plnkr.co/edit/qpo05FBWVUkSXLtEPH0W?p=preview.

**Comment by indrimuska** [comment]
I have closed this issue, feel free to reopen it if you still have any trouble!
