### ISSUE TITLE
Stop min-date/max-date from auto adjusting value

### ISSUE THREAD

**Issue by ChrisB92** [indrimuska/angular-moment-picker#76]
Hi there

I'm currently experiencing an issue (to me) where if you have `min-date` set to 10:30 and you enter 10:20 it will automatically change the value to 10:30. Is it possible to set a property to disable this and trigger a validation error instead? It isn't clear to the user that the input has changed automatically and I would rather it told the user that the input is invalid.

Thanks,
Chris

**Comment by indrimuska** [comment]
Hi @ChrisB92, this is not possible at the moment, but it will surely be a nice feature.
Do you want to propose a PR for this?

**Comment by dariusbakunas** [comment]
I second this, would be nice to show validation errors instead of adjusting the value automatically. I think it could be made configurable and then my guess is just modifying checkValue/checkView functions to reflect this

**Comment by indrimuska** [comment]
FYI, setting `validate="false"` will allow you to raise `minDate` and `maxDate` errors every time the value of the picker gets out of bound -- available  starting from [v0.8.4](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.8.4).
