### ISSUE TITLE
Hour view inconsistency 

### ISSUE THREAD

**Issue by Nico924** [indrimuska/angular-moment-picker#79]
In the hour view, would it possible to keep the full number of the hour part selected in the day view ?
Example : you select 13:00 in the day view, in the hour view you see 1:00, 1:05, ... I think it would be preferable (especially in not 'en' locale) to display 13:00, 13:05, ...

Thank you in advance ! 
![capture d ecran 2016-11-08 a 15 02 45](https://cloud.githubusercontent.com/assets/3044305/20102147/41b15014-a5c5-11e6-883f-eefab854547c.png)

**Comment by indrimuska** [comment]
Hi @Nico924, you can change this setting using the momentPickerProvider:
```javascript
angular
    .module('myApp', ['moment-picker'])
    .config(['momentPickerProvider', function (momentPickerProvider) {
        momentPickerProvider.options({
            minutesFormat: "HH:mm"
        });
    }]);
```

**Comment by Nico924** [comment]
Oh indeed thank you ! I didn't go far enough in your documentation sorry ^^

Anyway I love your datepicker, good job !
