### ISSUE TITLE
Infdig error when using batarang on Chrome

### ISSUE THREAD

**Issue by ip512** [indrimuska/angular-moment-picker#8]
I have the following error when using moment-picker and batarang on chrome:
`Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!`
I disable batarang to fix the issue, so it's no more a blocking issue. I just sent this post to avoid others spending hours to figure out where these errors are coming from.

**Comment by indrimuska** [comment]
Thank you @ip512 for reporting this, I will investigate on what causes this issue.

**Comment by eversoclever** [comment]
I have a similar error in Chrome, but I'm not sure if I'm using Batarang or not (sorry, new at this):

Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"fn: function () {\n        var start = perf.now();\n        var ret = thatScope.$eval(watchExpression);\n        var end = perf.now();\n        _digestEvents.push({\n          eventType: 'scope:watch',\n          id: scopeId,\n          watch: watchStr,\n          time: end - start\n        });\n        return ret;\n      }","newVal":["day","hour"],"oldVal":["day","hour"]}],[{"msg":"fn: function () {\n        var start = perf.now();\n        var ret = thatScope.$eval(watchExpression);\n        var end = perf.now();\n        _digestEvents.push({\n          eventType: 'scope:watch',\n          id: scopeId,\n          watch: watchStr,\n          time: end - start\n        });\n        return ret;\n      }","newVal":["day","hour"],"oldVal":"..."}],[{"msg":"fn: function () {\n        var start = perf.now();\n        var ret = thatScope.$eval(watchExpression);\n        var end = perf.now();\n        _digestEvents.push({\n          eventType: 'scope:watch',\n          id: scopeId,\n          watch: watchStr,\n          time: end - start\n        });\n        return ret;\n      }","newVal":["day","hour"],"oldVal":"..."}],[{"msg":"fn: function () {\n        var start = perf.now();\n        var ret = thatScope.$eval(watchExpression);\n        var end = perf.now();\n        _digestEvents.push({\n          eventType: 'scope:watch',\n          id: scopeId,\n          watch: watchStr,\n          time: end - start\n        });\n        return ret;\n      }","newVal":["day","hour"],"oldVal":"..."}],[{"msg":"fn: function () {\n        var start = perf.now();\n        var ret = thatScope.$eval(watchExpression);\n        var end = perf.now();\n        _digestEvents.push({\n          eventType: 'scope:watch',\n          id: scopeId,\n          watch: watchStr,\n          time: end - start\n        });\n        return ret;\n      }","newVal":["day","hour"],"oldVal":"..."}]]
http://errors.angularjs.org/1.4.9/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22ms…wVal%22%3A%5B%22day%22%2C%22hour%22%5D%2C%22oldVal%22%3A%22...%22%7D%5D%5D
    at angular.js:68
    at Scope.$digest (angular.js:16133)
    at Scope.scopePrototype.$digest (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2016)
    at Scope.$apply (angular.js:16359)
    at Scope.scopePrototype.$apply (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2079)
    at done (angular.js:10791)
    at completeRequest (angular.js:10989)
    at XMLHttpRequest.requestLoaded (angular.js:10930)(anonymous function) @ angular.js:12722
angular.js:16362 Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"fn: function () {\n        var start = perf.now();\n        var ret = thatScope.$eval(watchExpression);\n        var end = perf.now();\n        _digestEvents.push({\n          eventType: 'scope:watch',\n          id: scopeId,\n          watch: watchStr,\n          time: end - start\n        });\n        return ret;\n      }","newVal":["day","hour"],"oldVal":["day","hour"]}],[{"msg":"fn: function () {\n        var start = perf.now();\n        var ret = thatScope.$eval(watchExpression);\n        var end = perf.now();\n        _digestEvents.push({\n          eventType: 'scope:watch',\n          id: scopeId,\n          watch: watchStr,\n          time: end - start\n        });\n        return ret;\n      }","newVal":["day","hour"],"oldVal":"..."}],[{"msg":"fn: function () {\n        var start = perf.now();\n        var ret = thatScope.$eval(watchExpression);\n        var end = perf.now();\n        _digestEvents.push({\n          eventType: 'scope:watch',\n          id: scopeId,\n          watch: watchStr,\n          time: end - start\n        });\n        return ret;\n      }","newVal":["day","hour"],"oldVal":"..."}],[{"msg":"fn: function () {\n        var start = perf.now();\n        var ret = thatScope.$eval(watchExpression);\n        var end = perf.now();\n        _digestEvents.push({\n          eventType: 'scope:watch',\n          id: scopeId,\n          watch: watchStr,\n          time: end - start\n        });\n        return ret;\n      }","newVal":["day","hour"],"oldVal":"..."}],[{"msg":"fn: function () {\n        var start = perf.now();\n        var ret = thatScope.$eval(watchExpression);\n        var end = perf.now();\n        _digestEvents.push({\n          eventType: 'scope:watch',\n          id: scopeId,\n          watch: watchStr,\n          time: end - start\n        });\n        return ret;\n      }","newVal":["day","hour"],"oldVal":"..."}]]
http://errors.angularjs.org/1.4.9/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22ms…wVal%22%3A%5B%22day%22%2C%22hour%22%5D%2C%22oldVal%22%3A%22...%22%7D%5D%5D

**Comment by ip512** [comment]
when batarang is active, you have an angular icon in your address bar

**Comment by bduebel** [comment]
Found the extension. Disabled it. Everything is back to normal.

**Comment by superdecimal** [comment]
+1 I stumbled upon this error yesterday.

**Comment by christianklock-iglu** [comment]
+1 
I created a simple test app which worked with the extension enabled. At the same time, using the extension in our huge webapp, I keep receiving the error above. So, I believe we see some kind of cross-interaction of possible different libraries and the extension.

**Comment by flyingboy007** [comment]
+1 never thought that

**Comment by indrimuska** [comment]
It seems the [latest release](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.6.0) is not affected by this issue.
I don't know why, but one the major updates consist on how the picker is closed (see [this](https://github.com/indrimuska/angular-moment-picker/blob/0.5.7/src/angular-moment-picker.js#L227-L229) and [this](https://github.com/indrimuska/angular-moment-picker/blob/0.5.7/src/angular-moment-picker.js#L590-L596)). Maybe someone of you will be able to understand why this was happening.
Thank you all for your support. :)

**Comment by deifos** [comment]
I have just download the library with bower and  I get the same error, however if I use the code from the ngmodel_support branch, it works fine with batarang on.

**Comment by indrimuska** [comment]
Damn, @deifos you're right, this issue still persist in the latest version of the directive.
However, can you please make a test with the new branch I'm working at (`return-moment-object`) in order to check if this issue can be closed with the next major release?

Plunker and more infos about the branch: [here](https://github.com/indrimuska/angular-moment-picker/issues/60#issuecomment-254596657).
Thanks

**Comment by indrimuska** [comment]
Closed by #91.
