### ISSUE TITLE
from and to date value

### ISSUE THREAD

**Issue by sadashivm** [indrimuska/angular-moment-picker#80]
Hi,
it is one of the best lightweight angular date picker . i really liked it.

im using two date like Start and End date example as bellow.

**Start Date** : <input type="text" moment-picker="startDate" format="DD/MM/YYYY" ng-model="startDate" start-view="month" />

**End Date** : <input type="text" moment-picker="endDate" format="DD/MM/YYYY" ng-model="endDate" start-view="month" />

for example if i select start date 15/05/2016 then i need EndDate start from 15/05/2016 and above. And disable all bellow 15/05/2016 in Enddate picker.

so what should i do for above problem because range picker example is not added in example. i would like request to you can u do it as early as possible

**Comment by indrimuska** [comment]
Hi @sadashivm, you can simply do something like that (remember to use the same `format`):

```html
<!-- start date -->
<input class="form-control"
       placeholder="Start date..."
       ng-model="startDate"
       moment-picker="startDate"
       format="YYYY-MM-DD"
       max-date="endDate">

<!-- end date -->
<input class="form-control"
       placeholder="End date..."
       ng-model="endDate"
       moment-picker="endDate"
       format="YYYY-MM-DD"
       min-date="startDate">
```
