### ISSUE TITLE
how reset the picker?

### ISSUE THREAD

**Issue by claus1982** [indrimuska/angular-moment-picker#82]
Is there a way to reset the picker programmatically?

**Comment by indrimuska** [comment]
Hi @claus1982, why can't you simply set your model to a null or blank value?

**Comment by claus1982** [comment]
it doesn't work, if I try to do put it undefined programmatically, it
doesn't change

Il 09 Nov 2016 23:13, "indrimuska" <notifications@github.com> ha scritto:

**Comment by jl-yang-arm** [comment]
yes, so how could it be reset to default/defined date?

**Comment by er-sarjan** [comment]
@claus1982, I tried to set undefined and it change to previous selected value so set it to null

**Comment by jl-yang-arm** [comment]
E.g. year is selected to another value but date selection is not completed, so now could the picker be reset to previous year after the focus of the picker is lost?

**Comment by indrimuska** [comment]
Please, verify if you still have this issue in the [latest release](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.7.1).

**Comment by chandanv03** [comment]
Hi @indrimuska  ,

i have initally set the minDate to $scope,minDate=moment(); //this will set to current date 
now i select a different date from date picker , if i want to reset the selected date to current date 
how can i achieve this ?? i don't want to set to null or undefined or "" 
please help me about this .

**Comment by jl-yang-arm** [comment]
@indrimuska no, as @chandanv03 mentioned, it is unable to reset to current date for example, verified in latest release also.

**Comment by indrimuska** [comment]
Wait, resetting a date to a null value and set it to the current date are two different things.
Ok, if you just need to set the model to the current date you simply have to set it in the format you have choosen by the `format` property:

```
<input class="form-control"
       ng-model="ctrl.input"
       format="YYYY-MM-DD"
       ng-model-options="{ updateOn: 'blur' }"
       placeholder="Select a date..."
       moment-picker="ctrl.input">

<button class="btn btn-default"
        ng-click="ctrl.resetDate()">
   Reset date
</button>
```

```
ctrl.resetDate = function () {
   ctrl.input = moment().format('YYYY-MM-DD');
};
```

**Comment by chandanv03** [comment]
Hi @indrimuska ,

Thanks a lot for you reply , but reset is not working .

see my below code:
  <input class="form-control"
                                   ng-model="minDate"
                                   data-max-date="minDate"
                                   id="min-date"
                                   format="YYYY/MM/DD hh:mm:ss"
                                   name="minDate"
                                   ng-model-options="{updateOn: 'blur'}"
                                   placeholder="Begin Date & Time"
                                   moment-picker="minDate" required>                                   
                                  <a class="clear" ng-click="resetDate()">X</a>


         $scope.minDate=moment();
        $scope.maxDate=moment();


        $scope.resetDate= function(){            
            $scope.minDate= moment().format('YYYY/MM/DD hh:mm:ss');
        }

if i use below code it works , 

 $scope.resetDate= function(){            
            $scope.minDate= moment().format('L LTS');
        } 

but the format gets changed to 11/25/2016 1:12:19 PM  which is not YYY/MM/DD 
how can i achieve this to show in same format as  "YYYY/MM/DD hh:mm:ss"?
Please help me on this

**Comment by indrimuska** [comment]
Well, I don't know your case, but it should work with the instruction I gave you.
Maybe [this plunker](https://plnkr.co/edit/rdLTdSetGbhVHt3xI5T3?p=preview) could help figure out why for you it's not working.
