### ISSUE TITLE
ng-required Passthrough

### ISSUE THREAD

**Issue by ChrisGarber-Medlever** [indrimuska/angular-moment-picker#84]
Would it be possible to extend this to use angular validation? All that would be required is a passthrough of a "required" variable e.g. required = "expression" or ng-required = "exp", then a call to ng-required on the input field.

**Comment by indrimuska** [comment]
Hi @ChrisGarber-Medlever, as for issue #76, this is part of picker validation topic, that actually is not implemented. I don't have much spare time in this period, so I don't know when this feature will be implemented.

Any help would be always welcome! :)

**Comment by indrimuska** [comment]
FYI, starting from latest release you can make use of `ngRequired` directive (or `required` in combination with `ngModel`) to set validity status rule for your picker.
