### ISSUE TITLE
Version 0.7.1 - input element error

### ISSUE THREAD

**Issue by marchioreto** [indrimuska/angular-moment-picker#85]
Hi,

Picker doesn't work for input element in version 0.7.1. With div element the picker works fine. 

The demo page (http://indrimuska.github.io/angular-moment-picker/) also has  the error.

Thanks,
Marchioreto

**Comment by HelloYu** [comment]
same issue here.

**Comment by indrimuska** [comment]
Thank you guys for reporting this, that's due to the transclusion of `<input>` field (an input element cannot have drawable DOM node child). I'll find a way to fix this as soon as I can :)

**Comment by indrimuska** [comment]
FYI, this should be fixed in [v0.7.2](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.7.2). Give it a try! :)
