### ISSUE TITLE
Cannot get desired format + datetime value 2 hours behind

### ISSUE THREAD

**Issue by KarishImrith** [indrimuska/angular-moment-picker#94]
Hi There,

`{{employee.StartingDate}}
                <div class="form-group">
                    <label class="col-sm-2 control-label">Starting Date:</label>
                    <div class="col-sm-10">
                        <div class="form-control" ng-model-options="{ updateOn: 'blur' }" moment-picker="employee.StartingDate" ng-model="employee.StartingDate">{{employee.StartingDate | date: 'dd MMM yyyy'}}</div>
                    </div>
                </div>`

I am using the above to attempt to use your datepicker for a date field. The datepicker will receive a date in the format 2019-04-03T22:00:00 from a web service via angular ng-model binding. I need it to work with this format as the value but for the display to be DD MMM YYYY. 

I am having the following issues:
1) When selecting a datetime with the picker, the valiable binded gets a value that is 2 hours behind.
2) The datepicker is not displaying in my desired format.

At Load:
![image](https://cloud.githubusercontent.com/assets/8863730/20751986/7497dd1a-b707-11e6-902f-cc65e192cbd9.png)

After selecting 1 June 2016 00:00:00
![image](https://cloud.githubusercontent.com/assets/8863730/20752024/b5f2ea98-b707-11e6-9bba-86dcb3afb472.png)

Please assist.

**Comment by indrimuska** [comment]
Hi @KarishImrith, there are several ways to achieve that goal (my advice is to read the README, you were using `ngModel` with a String value). If you want to keep using Angular's date filter you can do that:

   ```html
   <div class="form-group">
      <label class="col-sm-2 control-label">Starting Date:</label>
      <div class="col-sm-10">
         <div class="form-control"
              moment-picker="employee.StartingDate"
              format="YYYY-MM-DDTHH:MM:ss">
            {{employee.StartingDate | date: 'dd MMM yyyy'}}
         </div>
      </div>
   </div>
   ```
