### ISSUE TITLE
predefined date is not assigning to element

### ISSUE THREAD

**Issue by sadashivm** [indrimuska/angular-moment-picker#95]
Hi, 
in controller i defined date

```
$scope.dt = {
    startDate : '24/11/2016'
}
```

in view page

`<input type="text" moment-picker  ng-model="dt.startDate" format="DD/MM/YYYY" start-view="month" ng-model-options="{ updateOn: 'blur' }" />`

the problem is when i  run the code date is not assigning to the element. i mean date is not displaying in textbox. i would like to request to you pls solve this problem as early as possible

**Comment by indrimuska** [comment]
Hi @sadashivm, you are not using the properties of the picker in the correct way.
You should check out at [this comment](https://github.com/indrimuska/angular-moment-picker/issues/92#issuecomment-263669991) and have a look at the README file.

Hope this helps!

**Comment by indrimuska** [comment]
In your case, you have to update your template like this:

```html
input type="text" moment-picker="dt.startDate" ng-model="dt.startDateMoment" format="DD/MM/YYYY" start-view="month" ng-model-options="{ updateOn: 'blur' }">
```

You don't need to use `dt.startDateMoment`, but it is required to properly initialize an input element.

**Comment by chillyprig** [comment]
Here is my markup:

`<input class="form-control" ng-model="Model.seminar.date" ng-model-options="{ updateOn: 'blur' }" name="date"
               placeholder="Select a date..." moment-picker="Model.seminar.date" required>`

Here is my Controller:

`$scope.Model.seminar = {
                     date: moment()
                 };`

Still nothing show in my input though

**Comment by indrimuska** [comment]
Ok, first keep in mind the usage of the main properties:

> Property | Description
> ---|---
> moment-picker | Two-way bindable property as **formatted datetime string**.
> ng-model | Two-way bindable property as **Moment.js object**.

If you set the same value for both properties (`Model.seminar.date`) you will get a Moment.js object.
Anyway, you should see your input populated with the right formatted date.
Check out [this plunker](https://plnkr.co/edit/wFfamOnDL1SvQuitTmPX?p=preview).

Would you please provide a full working example that reproduces this issue?
Thanks

**Comment by flyfap** [comment]
Hi! When the page is loaded I want the picker to be set with data from the API. I have tried to assign the date to the corresponding $scope of "moment-picker" but the changes are not displayed. Nor I have achieved it by using the "start-date" attribute.

**Comment by archesh5001** [comment]
Hello,  I have been following this comment chain and even I am not able to fix this issue. Can you please look in to this? In my scenario, I am storing the moment object from the ng-model in to a JSON payload. Later, when the UI reads the payload again, the date field doesn't populate back from the  ng-model although the moment object is still there.

**Comment by wiggitamoo** [comment]
I also have the same issue as mentioned in the above two posts. A fix to initialize the moment picker at startup would be very helpful.

**Comment by flyfap** [comment]
Hi, I have fixed the problem. I was using Bower instead of NPM, so I was using a very simillar package that is called the same. 🙁

I apologize and I hope this helps other people having the same issue.

**Comment by wiggitamoo** [comment]
Thanks for the quick fix. Is this change pushed in the 0.9.3 distribution?

**Comment by wiggitamoo** [comment]
I am also using bower in my application. Just to clarify, are you saying to use the NPM version of the library like this:

`npm install angular-moment-picker`

, or are you saying to install the library with bower still like this:

`bower install angular-moment-picker`

Thanks for your clarification.

**Comment by indrimuska** [comment]
[README](https://github.com/indrimuska/angular-moment-picker#installation) file shows how to get the project properly:

```
  npm install angular-moment-picker
bower install moment-picker
  git clone   https://github.com/indrimuska/angular-moment-picker.git
```

Pay attention and **do to not confuse** this project with the bower ones named `angular-moment-picker` (see https://github.com/indrimuska/angular-moment-picker/issues/109).

**Comment by wiggitamoo** [comment]
Yes @indrimuska that is correct. However, when using the bower install moment-picker (as specified in the README file, a predefined date is not being assigning to element.

**Comment by indrimuska** [comment]
Does bower install get different distribution files than npm install? Really?

**Comment by indrimuska** [comment]
I'm going to close this issue.
Feel free to reopen it if you have any trouble.
