### ISSUE TITLE
No tests!?

### ISSUE THREAD

**Issue by edouard-lopez** [indrimuska/angular-moment-picker#96]
~800 lines of code, 0 tests.

How do you prevent regression?

**Comment by indrimuska** [comment]
Hi @edouard-lopez, simply I do not. 😄 
Actually I am working on this library on my free time and, even if I really would like to write them and integrate inside the project, I can't find the time to do that.

Anyway, if you are interested to develop some basic test and make a PR I would be glad to review your code and help you write some other tests.

**Comment by indrimuska** [comment]
Last weekend I added first two tests and integrated in the Travis CI environment.
You can run all tests by typing `grunt test`.
Anyone who likes to contribute is welcome!
Thanks :)
